import { z } from "zod";

import { CAPA_STATE } from "../domain/capa-state";

/**
 * Runtime validation schemas for LVT CAPA.
 *
 * Primary sources:
 * Document #3 — LVT CAPA User Requirements Specification
 * Document #4 — LVT CAPA Workflow and State Specification
 * Document #8 — LVT CAPA Data Model and Audit-Trail Specification
 *
 * Traceability:
 * URS-ACC-001 through URS-ACC-010
 * URS-CASE-001 through URS-CASE-012
 * DM-COM-001 through DM-COM-009
 * WFR-001 through WFR-013
 *
 * Security rule:
 * Client request schemas must not accept authoritative organization,
 * actor, workflow, version, approval, or audit values from the browser.
 */

/**
 * Initial defensive input limits.
 *
 * These are implementation safety limits, not regulatory conclusions.
 * Changes require review because they affect stored controlled content.
 */
export const CAPA_INPUT_LIMITS = {
  initiating_event: 4_000,
  source_type: 64,
  source_reference: 500,
  organization_reference: 100,
} as const;

/**
 * UUID or equivalently collision-resistant identifier.
 *
 * This implementation initially accepts UUID text. The physical
 * identifier-generation mechanism remains an infrastructure decision.
 */
export const OpaqueIdSchema = z.uuid();

/**
 * UTC ISO 8601 timestamp.
 *
 * Authoritative timestamps must be generated or verified by the server.
 */
export const IsoDateTimeSchema = z.iso.datetime({
  offset: true,
});

/**
 * Positive integer used for record and immutable object versions.
 */
export const PositiveVersionSchema = z
  .number()
  .int()
  .positive();

/**
 * Controlled code with a conservative syntax.
 *
 * Registry membership must be checked separately against the applicable
 * approved registry version.
 */
export const ControlledCodeSchema = z
  .string()
  .trim()
  .min(1)
  .max(64)
  .regex(
    /^[A-Za-z][A-Za-z0-9._:-]*$/,
    "Controlled code contains unsupported characters.",
  );

/**
 * Approved workflow-state identifiers from Document #4.
 */
export const CapaStateIdSchema = z.enum(CAPA_STATE);

/**
 * Categories of attributable actors.
 */
export const ActorTypeSchema = z.enum([
  "human",
  "service",
  "agent",
  "system",
]);

/**
 * Runtime schema for an attributable actor reference.
 */
export const ActorReferenceSchema = z.strictObject({
  actor_type: ActorTypeSchema,
  actor_id: OpaqueIdSchema,
  actor_version: z
    .string()
    .trim()
    .min(1)
    .max(100)
    .optional(),
});

/**
 * Runtime schema for request and correlation trace fields.
 *
 * Values are normally supplied by trusted server middleware rather than
 * accepted from an ordinary browser request body.
 */
export const RequestTraceSchema = z.strictObject({
  request_id: OpaqueIdSchema,
  correlation_id: OpaqueIdSchema,
  idempotency_key: z
    .string()
    .trim()
    .min(1)
    .max(200)
    .optional(),
});

/**
 * User-provided initiating source information.
 */
export const CapaInitiatingSourceSchema = z.strictObject({
  source_type: ControlledCodeSchema.max(
    CAPA_INPUT_LIMITS.source_type,
  ),

  source_reference: z
    .string()
    .trim()
    .min(1)
    .max(CAPA_INPUT_LIMITS.source_reference)
    .optional(),
});

/**
 * Initial request body for creating an S00 Draft Intake CAPA.
 *
 * Deliberately excluded:
 * - organization_id
 * - capa_case_id and case_number
 * - owner_user_id
 * - workflow status
 * - record/version numbers
 * - creation timestamps and actor
 * - approval or audit fields
 *
 * Those values must be derived or generated by trusted server-side
 * application services.
 */
export const CreateCapaDraftRequestSchema = z.strictObject({
  initiating_event: z
    .string()
    .trim()
    .min(
      1,
      "Initiating event is required.",
    )
    .max(
      CAPA_INPUT_LIMITS.initiating_event,
      "Initiating event exceeds the permitted length.",
    ),

  source: CapaInitiatingSourceSchema,

  organization_reference: z
    .string()
    .trim()
    .min(1)
    .max(CAPA_INPUT_LIMITS.organization_reference)
    .optional(),
});

export type CapaStateIdInput = z.infer<
  typeof CapaStateIdSchema
>;

export type ActorReferenceInput = z.infer<
  typeof ActorReferenceSchema
>;

export type RequestTraceInput = z.infer<
  typeof RequestTraceSchema
>;

export type CreateCapaDraftRequest = z.infer<
  typeof CreateCapaDraftRequestSchema
>;