import type { CapaCaseId, CapaCaseVersionId, CorrelationId, RequestId } from "../domain/capa-types";
import { CapaActionPlanReviewAdvisoryServiceError } from "../ai/capa-action-plan-review-advisory-service";
import type { CapaApiLogger } from "./capa-route-handler";
import { SupabaseCapaContextError, type CapaRequestContext, type SupabaseCapaContextResolver, type SupabaseCapaSessionFacts } from "../../security/supabase-capa-context";
import { SupabaseCapaTenantAccessError } from "../../security/supabase-capa-durable-context";
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export interface CapaActionPlanReviewAdvisoryApiDependencies { readonly get_session_facts: () => Promise<SupabaseCapaSessionFacts | null>; readonly resolve_context: SupabaseCapaContextResolver; readonly create_advisory_service: (context: CapaRequestContext) => import("../ai/capa-action-plan-review-advisory-service").CapaActionPlanReviewAdvisoryService; readonly now: () => Date; readonly generate_uuid: () => string; readonly logger: CapaApiLogger; }
function response(body: unknown, status: number) { return Response.json(body, { status, headers: { "cache-control": "no-store" } }); }
function trace(request: Request, generate_uuid: () => string): { readonly request_id: RequestId; readonly correlation_id: CorrelationId } { const id = (value: string | null) => { const normalized = value?.trim() ?? ""; return UUID.test(normalized) ? normalized : generate_uuid(); }; return { request_id: id(request.headers.get("x-request-id")) as RequestId, correlation_id: id(request.headers.get("x-correlation-id")) as CorrelationId }; }
function error(trace_value: { readonly correlation_id: CorrelationId }, status: number, code: string, message: string) { return response({ error: { code, message, correlation_id: trace_value.correlation_id } }, status); }
function requestBody(value: unknown): { readonly expected_case_version_id: CapaCaseVersionId; readonly expected_record_version: number } { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new Error("INVALID_REQUEST"); const body = value as Record<string, unknown>; if (Object.keys(body).length !== 2 || typeof body.expected_case_version_id !== "string" || !UUID.test(body.expected_case_version_id) || typeof body.expected_record_version !== "number" || !Number.isSafeInteger(body.expected_record_version) || body.expected_record_version < 1) throw new Error("INVALID_REQUEST"); return { expected_case_version_id: body.expected_case_version_id as CapaCaseVersionId, expected_record_version: body.expected_record_version }; }
function mapped(trace_value: { readonly correlation_id: CorrelationId }, reason: CapaActionPlanReviewAdvisoryServiceError): Response | null { switch (reason.reason_code) { case "CASE_NOT_FOUND_OR_NOT_AUTHORIZED": return error(trace_value, 404, "CAPA_ADVISORY_CASE_NOT_FOUND", "The CAPA case was not found."); case "CASE_NOT_IN_ACTION_PLAN_REVIEW": return error(trace_value, 409, "CAPA_ADVISORY_CASE_STATE_CONFLICT", "The CAPA case is not in S70 Action Plan Review."); case "ADVISORY_ACCESS_DENIED": return error(trace_value, 403, "CAPA_ADVISORY_ACCESS_DENIED", "The CAPA action-plan review advisory operation is not authorized."); case "AGENT_NOT_ELIGIBLE": return error(trace_value, 409, "CAPA_ADVISORY_AGENT_NOT_ELIGIBLE", "The governed action-plan review advisory is not available for the current CAPA state."); case "WORKFLOW_MUTATION_DETECTED": return error(trace_value, 409, "CAPA_ADVISORY_CASE_CHANGED", "The CAPA case changed while the advisory was being generated."); default: return null; } }
export async function handleCapaActionPlanReviewAdvisoryPost(request: Request, caseId: string, dependencies: CapaActionPlanReviewAdvisoryApiDependencies): Promise<Response> { const request_trace = trace(request, dependencies.generate_uuid); try { const session = await dependencies.get_session_facts(); if (session === null) return error(request_trace, 401, "UNAUTHORIZED", "Authentication is required."); const context = await dependencies.resolve_context(session, dependencies.now()); if (!UUID.test(caseId)) return error(request_trace, 400, "INVALID_CAPA_CASE_ID", "A valid CAPA case identifier is required."); let body: unknown; try { body = await request.json(); } catch { return error(request_trace, 400, "INVALID_CAPA_ADVISORY_REQUEST", "The CAPA action-plan review advisory request is invalid."); } const result = await dependencies.create_advisory_service(context).execute({ organization_id: context.tenant.organization_id, capa_case_id: caseId as CapaCaseId, user_id: context.owner_user_id, request_id: request_trace.request_id, correlation_id: request_trace.correlation_id, request: requestBody(body) }); return response({ advisory: result.advisory, snapshot: result.snapshot, correlation_id: request_trace.correlation_id }, 201); } catch (caught) { if (caught instanceof SupabaseCapaContextError) return error(request_trace, 401, "INVALID_SESSION_CONTEXT", "The authenticated session is not valid for this request."); if (caught instanceof SupabaseCapaTenantAccessError) return error(request_trace, 403, "CAPA_TENANT_ACCESS_DENIED", "The authenticated user is not authorized to access a CAPA organization."); if (caught instanceof Error && caught.message === "INVALID_REQUEST") return error(request_trace, 400, "INVALID_CAPA_ADVISORY_REQUEST", "The CAPA action-plan review advisory request is invalid."); if (caught instanceof CapaActionPlanReviewAdvisoryServiceError) { const mapped_response = mapped(request_trace, caught); if (mapped_response !== null) return mapped_response; dependencies.logger.error("CAPA API action-plan review advisory failed.", { correlation_id: request_trace.correlation_id, error_name: caught.name, reason_code: caught.reason_code }); return error(request_trace, 500, "CAPA_INTERNAL_ERROR", "The CAPA request could not be completed."); } dependencies.logger.error("CAPA API action-plan review advisory failed.", { correlation_id: request_trace.correlation_id, error_name: caught instanceof Error ? caught.name : "UnknownError" }); return error(request_trace, 500, "CAPA_INTERNAL_ERROR", "The CAPA request could not be completed."); } }
