import type { CapaCaseId, CapaCaseVersionId, CorrelationId, RequestId } from "../domain/capa-types";
import { CapaImplementationEvidenceAdvisoryServiceError, type CapaImplementationEvidenceAdvisoryService } from "../ai/capa-implementation-evidence-advisory-service";
import type { CapaApiLogger } from "./capa-route-handler";
import { SupabaseCapaContextError, type CapaRequestContext, type SupabaseCapaContextResolver, type SupabaseCapaSessionFacts } from "../../security/supabase-capa-context";
import { SupabaseCapaTenantAccessError } from "../../security/supabase-capa-durable-context";

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export interface CapaImplementationEvidenceAdvisoryApiDependencies { readonly get_session_facts: () => Promise<SupabaseCapaSessionFacts | null>; readonly resolve_context: SupabaseCapaContextResolver; readonly create_advisory_service: (context: CapaRequestContext) => CapaImplementationEvidenceAdvisoryService; readonly now: () => Date; readonly generate_uuid: () => string; readonly logger: CapaApiLogger; }
function response(body: unknown, status: number): Response { return Response.json(body, { status, headers: { "cache-control": "no-store" } }); }
function trace(request: Request, generateUuid: () => string): { readonly request_id: RequestId; readonly correlation_id: CorrelationId } { const id = (value: string | null) => { const normalized = value?.trim() ?? ""; return UUID.test(normalized) ? normalized : generateUuid(); }; return { request_id: id(request.headers.get("x-request-id")) as RequestId, correlation_id: id(request.headers.get("x-correlation-id")) as CorrelationId }; }
function error(traceValue: { readonly correlation_id: CorrelationId }, status: number, code: string, message: string): Response { return response({ error: { code, message, correlation_id: traceValue.correlation_id } }, status); }
function body(value: unknown): { readonly expected_case_version_id: CapaCaseVersionId; readonly expected_record_version: number } { if (typeof value !== "object" || value === null || Array.isArray(value) || Object.keys(value).length !== 2 || typeof (value as Record<string, unknown>).expected_case_version_id !== "string" || !UUID.test((value as Record<string, unknown>).expected_case_version_id as string) || typeof (value as Record<string, unknown>).expected_record_version !== "number" || !Number.isSafeInteger((value as Record<string, unknown>).expected_record_version) || ((value as Record<string, unknown>).expected_record_version as number) < 1) throw new Error("INVALID_REQUEST"); return { expected_case_version_id: (value as Record<string, unknown>).expected_case_version_id as CapaCaseVersionId, expected_record_version: (value as Record<string, unknown>).expected_record_version as number }; }
function mapped(traceValue: { readonly correlation_id: CorrelationId }, failure: CapaImplementationEvidenceAdvisoryServiceError): Response | null { switch (failure.reason_code) { case "CASE_NOT_FOUND_OR_NOT_AUTHORIZED": return error(traceValue, 404, "CAPA_ADVISORY_CASE_NOT_FOUND", "The CAPA case was not found."); case "CASE_NOT_IN_IMPLEMENTATION": return error(traceValue, 409, "CAPA_ADVISORY_CASE_STATE_CONFLICT", "The CAPA case is not in S80 Implementation."); case "WORKSPACE_NOT_FOUND": return error(traceValue, 404, "CAPA_IMPLEMENTATION_WORKSPACE_NOT_FOUND", "The implementation workspace is not available."); case "APPROVED_S70_BASELINE_UNAVAILABLE": return error(traceValue, 409, "CAPA_APPROVED_BASELINE_UNAVAILABLE", "The approved S70 action-plan baseline is not available."); case "GOVERNED_KNOWLEDGE_UNAVAILABLE": return error(traceValue, 503, "CAPA_GOVERNED_KNOWLEDGE_UNAVAILABLE", "Governed knowledge context is not available."); case "ADVISORY_ACCESS_DENIED": return error(traceValue, 403, "CAPA_ADVISORY_ACCESS_DENIED", "The S80 advisory operation is not authorized."); case "AGENT_NOT_ELIGIBLE": return error(traceValue, 409, "CAPA_ADVISORY_AGENT_NOT_ELIGIBLE", "The governed S80 advisory is not available for the current CAPA state."); case "WORKFLOW_MUTATION_DETECTED": return error(traceValue, 409, "CAPA_ADVISORY_CASE_CHANGED", "The CAPA case changed while the advisory was being generated."); case "INVALID_ACTION_REFERENCE": return error(traceValue, 422, "CAPA_ADVISORY_INVALID_ACTION_REFERENCE", "The advisory contained an invalid approved-action reference."); case "INVALID_EVIDENCE_REFERENCE": return error(traceValue, 422, "CAPA_ADVISORY_INVALID_EVIDENCE_REFERENCE", "The advisory contained an invalid implementation-evidence reference."); case "INVALID_CITATION": return error(traceValue, 422, "CAPA_ADVISORY_INVALID_CITATION", "The advisory contained an invalid governed reference."); default: return null; } }
export async function handleCapaImplementationEvidenceAdvisoryPost(request: Request, caseId: string, dependencies: CapaImplementationEvidenceAdvisoryApiDependencies): Promise<Response> { const requestTrace = trace(request, dependencies.generate_uuid); try { const session = await dependencies.get_session_facts(); if (session === null) return error(requestTrace, 401, "UNAUTHORIZED", "Authentication is required."); const context = await dependencies.resolve_context(session, dependencies.now()); if (!UUID.test(caseId)) return error(requestTrace, 400, "INVALID_CAPA_CASE_ID", "A valid CAPA case identifier is required."); let parsed: unknown; try { parsed = await request.json(); } catch { return error(requestTrace, 400, "INVALID_CAPA_ADVISORY_REQUEST", "The S80 advisory request is invalid."); } const principal = context.authentication.principal; if (principal.principal_type !== "human") return error(requestTrace, 403, "AUTHORIZED_HUMAN_REQUIRED", "A human principal is required."); const result = await dependencies.create_advisory_service(context).execute({ organization_id: context.tenant.organization_id, capa_case_id: caseId as CapaCaseId, user_id: principal.user_id, request_id: requestTrace.request_id, correlation_id: requestTrace.correlation_id, request: body(parsed) }); return response({ advisory: result.advisory, snapshot: result.snapshot, correlation_id: requestTrace.correlation_id }, 201); } catch (caught) { if (caught instanceof SupabaseCapaContextError) return error(requestTrace, 401, "INVALID_SESSION_CONTEXT", "The authenticated session is not valid for this request."); if (caught instanceof SupabaseCapaTenantAccessError) return error(requestTrace, 403, "CAPA_TENANT_ACCESS_DENIED", "The authenticated user is not authorized to access a CAPA organization."); if (caught instanceof Error && caught.message === "INVALID_REQUEST") return error(requestTrace, 400, "INVALID_CAPA_ADVISORY_REQUEST", "The S80 advisory request is invalid."); if (caught instanceof CapaImplementationEvidenceAdvisoryServiceError) { const mappedResponse = mapped(requestTrace, caught); if (mappedResponse !== null) return mappedResponse; dependencies.logger.error("CAPA API S80 implementation-evidence advisory failed.", { correlation_id: requestTrace.correlation_id, error_name: caught.name, reason_code: caught.reason_code }); return error(requestTrace, 500, "CAPA_INTERNAL_ERROR", "The CAPA request could not be completed."); } dependencies.logger.error("CAPA API S80 implementation-evidence advisory failed.", { correlation_id: requestTrace.correlation_id, error_name: caught instanceof Error ? caught.name : "UnknownError" }); return error(requestTrace, 500, "CAPA_INTERNAL_ERROR", "The CAPA request could not be completed."); } }
