import type postgres from "postgres";
import type { CapaActionPlanReviewAdvisoryOutputRepository } from "../repositories/capa-action-plan-review-advisory-output-repository";
import { fingerprintCanonicalJson } from "../../capa/ai/capa-ai-generation-trace";
import type { TransactionContext } from "../transactions";
import { requireSupabaseTransaction } from "./supabase-transactions";
const MANIFEST_VERSION = "capa-action-plan-review-advisory-reference-manifest-1.0.0" as const;
export class SupabaseCapaActionPlanReviewAdvisoryOutputRepositoryError extends Error { constructor() { super("The governed S70 action-plan review advisory output could not be persisted."); this.name = "SupabaseCapaActionPlanReviewAdvisoryOutputRepositoryError"; } }
function json(value: unknown): postgres.JSONValue { try { return JSON.parse(JSON.stringify(value)) as postgres.JSONValue; } catch { throw new SupabaseCapaActionPlanReviewAdvisoryOutputRepositoryError(); } }
export class SupabaseCapaActionPlanReviewAdvisoryOutputRepository implements CapaActionPlanReviewAdvisoryOutputRepository {
  constructor(private readonly sql?: postgres.Sql) {}
  async findById(_organizationId: string, _outputId: string) { return null; }
  async save(transaction: TransactionContext, input: Parameters<CapaActionPlanReviewAdvisoryOutputRepository["save"]>[1]): Promise<"saved" | "case_changed"> {
    let sql: postgres.TransactionSql; try { sql = requireSupabaseTransaction(transaction); } catch { throw new SupabaseCapaActionPlanReviewAdvisoryOutputRepositoryError(); }
    if (transaction.request_trace.request_id !== input.request_id || transaction.request_trace.correlation_id !== input.correlation_id) throw new SupabaseCapaActionPlanReviewAdvisoryOutputRepositoryError();
    const manifestDocument = { manifest_schema_version: MANIFEST_VERSION, source_case_version_id: input.context.case_version_id, action_plan_section_version_id: input.context.sections.action_plan.section_version_id, entries: input.reference_manifest.map((entry) => ({ ...entry })) };
    const manifestHash = fingerprintCanonicalJson(manifestDocument);
    try {
      const current = await sql<postgres.Row[]>`select capa_case_id from public.capa_cases where organization_id = ${input.context.organization_id} and capa_case_id = ${input.context.capa_case_id} and current_version_id = ${input.context.case_version_id} and record_version = ${input.context.record_version} and status = 'S70' for update`;
      if (current.length !== 1) return "case_changed";
      const { response, generation_trace: trace } = input;
      const tracePackage = trace.package as { readonly trace: { readonly prompt_package_id: string; readonly assembled_at: string } };
      await sql`insert into public.capa_ai_outputs (organization_id, output_id, run_id, capa_case_id, case_version_id, record_version, request_id, correlation_id, agent_id, agent_version, output_schema_version, status, output_payload, advisory_only, workflow_mutated, human_acceptance_required, created_at) values (${input.context.organization_id}, ${response.output_id}, ${response.run_id}, ${input.context.capa_case_id}, ${input.context.case_version_id}, ${input.context.record_version}, ${input.request_id}, ${input.correlation_id}, 'AG-REVIEW', 'ag-review-1.0.0', ${response.output_schema_version}, ${response.status}, ${sql.json(json({ schema_version: response.output_schema_version, status: response.status, source_case_version_id: response.source_case_version_id, action_plan_section_version_id: response.action_plan_section_version_id, proposal: response.proposal, citations: [], advisory_only: true, workflow_mutated: false, controlled_record_mutated: false, approval_claimed: false, workflow_transition: null, human_acceptance_required: true }))}, true, false, true, ${transaction.started_at})`;
      await sql`insert into public.capa_ai_generation_traces (organization_id, run_id, output_id, capa_case_id, case_version_id, record_version, output_status, request_id, correlation_id, prompt_package_id, trace_schema_version, fingerprint_algorithm, prompt_package, prompt_package_sha256, rendered_prompt_sha256, evidence_manifest, evidence_manifest_sha256, policy_manifest, policy_manifest_sha256, model_profile_version, assembled_at) values (${input.context.organization_id}, ${response.run_id}, ${response.output_id}, ${input.context.capa_case_id}, ${input.context.case_version_id}, ${input.context.record_version}, ${response.status}, ${input.request_id}, ${input.correlation_id}, ${tracePackage.trace.prompt_package_id}, ${trace.trace_schema_version}, ${trace.fingerprints.algorithm}, ${sql.json(json(trace.package))}, ${trace.fingerprints.prompt_package_sha256}, ${trace.fingerprints.rendered_prompt_sha256}, ${sql.json(json(trace.evidence_manifest))}, ${trace.fingerprints.evidence_manifest_sha256}, ${sql.json(json(trace.policy_manifest))}, ${trace.fingerprints.policy_manifest_sha256}, ${trace.model_profile_version}, ${tracePackage.trace.assembled_at})`;
      await sql`insert into public.capa_ai_reference_manifests (organization_id, output_id, run_id, capa_case_id, case_version_id, record_version, request_id, correlation_id, output_status, manifest_schema_version, fingerprint_algorithm, reference_manifest, reference_manifest_sha256, created_at) values (${input.context.organization_id}, ${response.output_id}, ${response.run_id}, ${input.context.capa_case_id}, ${input.context.case_version_id}, ${input.context.record_version}, ${input.request_id}, ${input.correlation_id}, ${response.status}, ${MANIFEST_VERSION}, 'sha256-canonical-json-v1', ${sql.json(json(manifestDocument))}, ${manifestHash}, ${transaction.started_at})`;
      return "saved";
    } catch { throw new SupabaseCapaActionPlanReviewAdvisoryOutputRepositoryError(); }
  }
}
