import type postgres from "postgres";
import type { CapaActionPlanAdvisoryOutputRepository, CapaActionPlanAdvisoryOutputRecord, CapaActionPlanAdvisoryReferenceManifest } from "../repositories/capa-action-plan-advisory-output-repository";
import { fingerprintCanonicalJson } from "../../capa/ai/capa-ai-generation-trace";
import type { TransactionContext } from "../transactions";
import { requireSupabaseTransaction } from "./supabase-transactions";

const MANIFEST_VERSION = "capa-action-plan-advisory-reference-manifest-1.0.0" as const;
export class SupabaseCapaActionPlanAdvisoryOutputRepositoryError extends Error { constructor() { super("The governed S60 action-plan advisory output could not be persisted."); this.name = "SupabaseCapaActionPlanAdvisoryOutputRepositoryError"; } }
function json(value: unknown): postgres.JSONValue { try { return JSON.parse(JSON.stringify(value)) as postgres.JSONValue; } catch { throw new SupabaseCapaActionPlanAdvisoryOutputRepositoryError(); } }
export class SupabaseCapaActionPlanAdvisoryOutputRepository implements CapaActionPlanAdvisoryOutputRepository {
  constructor(private readonly sql?: postgres.Sql) {}
  async findById(_organizationId: string, _outputId: string): Promise<CapaActionPlanAdvisoryOutputRecord | null> { return null; }
  async save(transaction: TransactionContext, input: Parameters<CapaActionPlanAdvisoryOutputRepository["save"]>[1]): Promise<"saved" | "case_changed"> {
    let sql: postgres.TransactionSql; try { sql = requireSupabaseTransaction(transaction); } catch { throw new SupabaseCapaActionPlanAdvisoryOutputRepositoryError(); }
    if (transaction.request_trace.request_id !== input.request_id || transaction.request_trace.correlation_id !== input.correlation_id) throw new SupabaseCapaActionPlanAdvisoryOutputRepositoryError();
    const manifest: CapaActionPlanAdvisoryReferenceManifest = { document: { manifest_schema_version: MANIFEST_VERSION, entries: input.reference_manifest.map((entry) => ({ ...entry })) }, fingerprint_algorithm: "sha256-canonical-json-v1", reference_manifest_sha256: fingerprintCanonicalJson({ manifest_schema_version: MANIFEST_VERSION, entries: input.reference_manifest }) };
    try {
      const current = await sql<postgres.Row[]>`select capa_case_id from public.capa_cases where organization_id = ${input.context.organization_id} and capa_case_id = ${input.context.capa_case_id} and current_version_id = ${input.context.case_version_id} and record_version = ${input.context.record_version} and status = 'S60' for update`;
      if (current.length !== 1) return "case_changed";
      const { response, generation_trace: trace } = input;
      await sql`insert into public.capa_ai_outputs (organization_id, output_id, run_id, capa_case_id, case_version_id, record_version, request_id, correlation_id, agent_id, agent_version, output_schema_version, status, output_payload, advisory_only, workflow_mutated, human_acceptance_required, created_at) values (${input.context.organization_id}, ${response.output_id}, ${response.run_id}, ${input.context.capa_case_id}, ${input.context.case_version_id}, ${input.context.record_version}, ${input.request_id}, ${input.correlation_id}, 'AG-ACTION', 'ag-action-1.0.0', ${response.output_schema_version}, ${response.status}, ${sql.json(json({ schema_version: response.output_schema_version, status: response.status, proposal: response.proposal, warnings: response.warnings, uncertainty_and_limitations: response.uncertainty_and_limitations, citations: response.citations, advisory_only: true, workflow_mutated: false, controlled_record_mutated: false, approval_claimed: false, workflow_transition: null, human_acceptance_required: true }))}, true, false, true, ${transaction.started_at})`;
      await sql`insert into public.capa_ai_generation_traces (organization_id, run_id, output_id, capa_case_id, case_version_id, record_version, output_status, request_id, correlation_id, prompt_package_id, trace_schema_version, fingerprint_algorithm, prompt_package, prompt_package_sha256, rendered_prompt_sha256, evidence_manifest, evidence_manifest_sha256, policy_manifest, policy_manifest_sha256, model_profile_version, assembled_at) values (${input.context.organization_id}, ${response.run_id}, ${response.output_id}, ${input.context.capa_case_id}, ${input.context.case_version_id}, ${input.context.record_version}, ${response.status}, ${input.request_id}, ${input.correlation_id}, ${trace.package.trace.prompt_package_id}, ${trace.trace_schema_version}, ${trace.fingerprints.algorithm}, ${sql.json(json(trace.package))}, ${trace.fingerprints.prompt_package_sha256}, ${trace.fingerprints.rendered_prompt_sha256}, ${sql.json(json(trace.evidence_manifest))}, ${trace.fingerprints.evidence_manifest_sha256}, ${sql.json(json(trace.policy_manifest))}, ${trace.fingerprints.policy_manifest_sha256}, ${trace.model_profile_version}, ${trace.package.trace.assembled_at})`;
      await sql`insert into public.capa_ai_reference_manifests (organization_id, output_id, run_id, capa_case_id, case_version_id, record_version, request_id, correlation_id, output_status, manifest_schema_version, fingerprint_algorithm, reference_manifest, reference_manifest_sha256, created_at) values (${input.context.organization_id}, ${response.output_id}, ${response.run_id}, ${input.context.capa_case_id}, ${input.context.case_version_id}, ${input.context.record_version}, ${input.request_id}, ${input.correlation_id}, ${response.status}, ${MANIFEST_VERSION}, ${manifest.fingerprint_algorithm}, ${sql.json(json(manifest.document))}, ${manifest.reference_manifest_sha256}, ${transaction.started_at})`;
      return "saved";
    } catch { throw new SupabaseCapaActionPlanAdvisoryOutputRepositoryError(); }
  }
}
