import type { CapaContainmentRiskAdvisoryResponse, RawCapaContainmentRiskAdvisoryModelOutput } from "./capa-containment-risk-advisory-contract";
import { validateCapaContainmentRiskAdvisoryModelOutput } from "./capa-containment-risk-advisory-output-validator";
import type { CapaContainmentRiskAdvisoryContextAssembly } from "./capa-containment-risk-advisory-context";
import { buildCapaContainmentRiskAdvisoryPrompt } from "./capa-containment-risk-advisory-prompt";
import { createCapaContainmentRiskAdvisoryGenerationTrace } from "./capa-ai-generation-trace";
import { CAPA_CONTAINMENT_RISK_ADVISORY_EVIDENCE_GAP_CATEGORIES, CAPA_CONTAINMENT_RISK_ADVISORY_IMPACT_DIMENSIONS, CAPA_CONTAINMENT_RISK_ADVISORY_RISK_INPUT_TOPICS, CAPA_CONTAINMENT_RISK_ADVISORY_ASSUMPTION_AREAS, CAPA_CONTAINMENT_RISK_ADVISORY_UNCERTAINTY_CATEGORIES } from "./capa-containment-risk-advisory-contract";
import type { CapaAiOutputId, CapaAiRunId, CapaPromptPackageId } from "./capa-prompt-contract";
import type { CorrelationId, IsoDateTime, RequestId } from "../domain/capa-types";

export const CAPA_CONTAINMENT_RISK_ADVISORY_MODEL_PROFILE = Object.freeze({ profile_version: "capa-model-profile-1.0.0" as const, output_schema_name: "capa_containment_risk_advisory_1_0_0" as const, maximum_output_characters: 30_000 });
const question = { type: "string" } as const;
export const CAPA_CONTAINMENT_RISK_ADVISORY_JSON_SCHEMA = Object.freeze({ type: "object", additionalProperties: false, required: ["proposal", "assumptions", "uncertainty_and_limitations", "citations", "advisory_only", "workflow_mutated", "human_acceptance_required"], properties: { proposal: { type: "object", additionalProperties: false, required: ["missing_risk_inputs", "missing_impact_dimensions", "human_review_questions", "evidence_provenance_gaps"], properties: { missing_risk_inputs: { type: "array", items: { type: "object", additionalProperties: false, required: ["topic", "human_review_question"], properties: { topic: { type: "string", enum: [...CAPA_CONTAINMENT_RISK_ADVISORY_RISK_INPUT_TOPICS] }, human_review_question: question } } }, missing_impact_dimensions: { type: "array", items: { type: "object", additionalProperties: false, required: ["dimension", "human_review_question"], properties: { dimension: { type: "string", enum: [...CAPA_CONTAINMENT_RISK_ADVISORY_IMPACT_DIMENSIONS] }, human_review_question: question } } }, human_review_questions: { type: "array", items: question }, evidence_provenance_gaps: { type: "array", items: { type: "object", additionalProperties: false, required: ["category", "human_review_question"], properties: { category: { type: "string", enum: [...CAPA_CONTAINMENT_RISK_ADVISORY_EVIDENCE_GAP_CATEGORIES] }, human_review_question: question } } } } }, assumptions: { type: "array", items: { type: "object", additionalProperties: false, required: ["unverified", "related_area", "verification_question"], properties: { unverified: { const: true }, related_area: { type: "string", enum: [...CAPA_CONTAINMENT_RISK_ADVISORY_ASSUMPTION_AREAS] }, verification_question: question } } }, uncertainty_and_limitations: { type: "array", items: { type: "object", additionalProperties: false, required: ["category", "human_review_question"], properties: { category: { type: "string", enum: [...CAPA_CONTAINMENT_RISK_ADVISORY_UNCERTAINTY_CATEGORIES] }, human_review_question: question } } }, citations: { type: "array", maxItems: 0, items: {} }, advisory_only: { const: true }, workflow_mutated: { const: false }, human_acceptance_required: { const: true } } } as const);
export interface CapaContainmentRiskAdvisoryStructuredModelClient { generateStructured(input: { readonly prompt: string; readonly model_profile_version: typeof CAPA_CONTAINMENT_RISK_ADVISORY_MODEL_PROFILE.profile_version; readonly output_schema_name: typeof CAPA_CONTAINMENT_RISK_ADVISORY_MODEL_PROFILE.output_schema_name; readonly output_schema: typeof CAPA_CONTAINMENT_RISK_ADVISORY_JSON_SCHEMA; readonly maximum_output_characters: number; readonly store: false }): Promise<{ readonly output_text: string }>; }
export interface CapaContainmentRiskAdvisoryGenerationInput { readonly context: CapaContainmentRiskAdvisoryContextAssembly; readonly focus?: string | null; readonly request_id: RequestId; readonly correlation_id: CorrelationId; }
export interface CapaContainmentRiskAdvisoryModelGeneratorDependencies { readonly model_client: CapaContainmentRiskAdvisoryStructuredModelClient; readonly createRunId: () => CapaAiRunId; readonly createPromptPackageId: () => CapaPromptPackageId; readonly now: () => IsoDateTime; readonly createOutputId: () => CapaAiOutputId; }
export class CapaContainmentRiskAdvisoryModelGenerator {
  constructor(private readonly dependencies: CapaContainmentRiskAdvisoryModelGeneratorDependencies) {}
  async generate(input: CapaContainmentRiskAdvisoryGenerationInput): Promise<{ readonly response: CapaContainmentRiskAdvisoryResponse; readonly trace: import("./capa-ai-generation-trace").CapaContainmentRiskAdvisoryGenerationTraceCapture }> {
    const run_id = this.dependencies.createRunId();
    const prompt_package_id = this.dependencies.createPromptPackageId();
    const assembled_at = this.dependencies.now();
    const prompt = buildCapaContainmentRiskAdvisoryPrompt(input);
    if (typeof prompt !== "string" || prompt.trim().length === 0 || prompt.length > 120_000) throw new Error("CONTROLLED_CAPA_PROMPT_INVALID");
    const trace = createCapaContainmentRiskAdvisoryGenerationTrace({ rendered_prompt: prompt, model_profile_version: CAPA_CONTAINMENT_RISK_ADVISORY_MODEL_PROFILE.profile_version, output_schema_name: CAPA_CONTAINMENT_RISK_ADVISORY_MODEL_PROFILE.output_schema_name, output_schema: CAPA_CONTAINMENT_RISK_ADVISORY_JSON_SCHEMA, maximum_output_characters: CAPA_CONTAINMENT_RISK_ADVISORY_MODEL_PROFILE.maximum_output_characters, package: { scope: { ...input.context.authoritative }, agent: { agent_id: "AG-INTAKE", agent_version: "ag-intake-1.0.0" }, trace: { run_id, prompt_package_id, request_id: input.request_id, correlation_id: input.correlation_id, assembled_at }, context_provenance: { authoritative_server_context: input.context.authoritative, untrusted_human_draft: input.context.untrusted_human_draft, focus: input.focus ?? null }, governance: { advisory_only: true, workflow_mutated: false, human_acceptance_required: true } }, policy_manifest: { agent: { agent_id: "AG-INTAKE", agent_version: "ag-intake-1.0.0" }, workflow_state: "S20", operation: "analyze_containment_impact_risk", requested_output: "containment_risk_analysis", output_schema_version: "capa-containment-risk-advisory-1.0.0", generation: { model_profile_version: CAPA_CONTAINMENT_RISK_ADVISORY_MODEL_PROFILE.profile_version, output_schema_name: CAPA_CONTAINMENT_RISK_ADVISORY_MODEL_PROFILE.output_schema_name }, authority: { advisory_only: true, workflow_mutated: false, human_acceptance_required: true }, prohibitions: ["risk acceptance", "approval", "release", "distribution", "continued use", "recall", "field action", "reportability", "containment approval", "G-02", "controlled-record mutation", "workflow advancement", "evidence verification", "review disposition"] } });
    const raw = await this.dependencies.model_client.generateStructured({ prompt, model_profile_version: CAPA_CONTAINMENT_RISK_ADVISORY_MODEL_PROFILE.profile_version, output_schema_name: CAPA_CONTAINMENT_RISK_ADVISORY_MODEL_PROFILE.output_schema_name, output_schema: CAPA_CONTAINMENT_RISK_ADVISORY_JSON_SCHEMA, maximum_output_characters: CAPA_CONTAINMENT_RISK_ADVISORY_MODEL_PROFILE.maximum_output_characters, store: false });
    const advisory = validateCapaContainmentRiskAdvisoryModelOutput(raw.output_text);
    const output_id = this.dependencies.createOutputId();
    const response: CapaContainmentRiskAdvisoryResponse = Object.freeze({ run_id: run_id, output_id, output_schema_version: "capa-containment-risk-advisory-1.0.0" as CapaContainmentRiskAdvisoryResponse["output_schema_version"], status: "completed_draft", proposal: advisory.proposal, containment_summary: Object.freeze([]), citations: Object.freeze([]), assumptions: advisory.assumptions, uncertainty_and_limitations: advisory.uncertainty_and_limitations, warnings: Object.freeze([]), advisory_only: true, workflow_mutated: false, human_acceptance_required: true });
    return Object.freeze({ response, trace });
  }
}
