import type { CapaAiOutputId, CapaAiRunId, CapaPromptPackageId } from "./capa-prompt-contract";
import type { CorrelationId, IsoDateTime, RequestId } from "../domain/capa-types";
import type { CapaActionPlanReviewAdvisoryContextAssembly } from "./capa-action-plan-review-advisory-context";
import { CAPA_ACTION_PLAN_REVIEW_ADVISORY_CATEGORIES, CAPA_ACTION_PLAN_REVIEW_ADVISORY_DISPOSITIONS, CAPA_ACTION_PLAN_REVIEW_ADVISORY_OUTPUT, CAPA_ACTION_PLAN_REVIEW_ADVISORY_OUTPUT_SCHEMA_VERSION, CAPA_ACTION_PLAN_REVIEW_ADVISORY_SEVERITIES, type CapaActionPlanReviewAdvisoryResponse } from "./capa-action-plan-review-advisory-contract";
import { validateCapaActionPlanReviewAdvisoryModelOutput } from "./capa-action-plan-review-advisory-validator";
import { CAPA_AI_GENERATION_FINGERPRINT_ALGORITHM, CAPA_AI_GENERATION_TRACE_SCHEMA_VERSION, deepFreezeCapaAiGenerationTraceValue, fingerprintCanonicalJson, sha256Utf8, snapshotCapaAiGenerationTraceValue } from "./capa-ai-generation-trace";

export const CAPA_ACTION_PLAN_REVIEW_ADVISORY_MODEL_PROFILE = Object.freeze({ profile_version: "capa-action-plan-review-advisory-model-profile-1.0.0", output_schema_name: "capa_action_plan_review_advisory_1_0_0", output_schema_version: CAPA_ACTION_PLAN_REVIEW_ADVISORY_OUTPUT_SCHEMA_VERSION, maximum_output_characters: 40_000 } as const);
const text = { type: "string", minLength: 1, maxLength: 4_000 } as const;
const uuid = { type: "string", pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$" } as const;
const controlledId = { type: "string", minLength: 1, maxLength: 128 } as const;
const refs = { type: "array", maxItems: 40, items: { type: "string", pattern: "^R[1-9][0-9]{0,2}$" } } as const;
const finding = { type: "object", additionalProperties: false, required: ["finding_id", "category", "severity", "summary", "rationale", "affected_action_ids", "affected_root_cause_ids", "reference_keys", "suggested_reviewer_attention"], properties: { finding_id: { type: "string", pattern: "^[A-Za-z][A-Za-z0-9._:-]{0,127}$" }, category: { type: "string", enum: [...CAPA_ACTION_PLAN_REVIEW_ADVISORY_CATEGORIES] }, severity: { type: "string", enum: [...CAPA_ACTION_PLAN_REVIEW_ADVISORY_SEVERITIES] }, summary: text, rationale: text, affected_action_ids: { type: "array", maxItems: 40, items: controlledId }, affected_root_cause_ids: { type: "array", maxItems: 40, items: controlledId }, reference_keys: refs, suggested_reviewer_attention: text } } as const;
export const CAPA_ACTION_PLAN_REVIEW_ADVISORY_JSON_SCHEMA = Object.freeze({ type: "object", additionalProperties: false, required: ["schema_version", "status", "source_case_version_id", "action_plan_section_version_id", "proposal", "citations", "advisory_only", "workflow_mutated", "controlled_record_mutated", "approval_claimed", "workflow_transition", "human_acceptance_required"], properties: { schema_version: { type: "string", const: CAPA_ACTION_PLAN_REVIEW_ADVISORY_OUTPUT_SCHEMA_VERSION }, status: { type: "string", const: "completed_draft" }, source_case_version_id: uuid, action_plan_section_version_id: uuid, proposal: { type: "object", additionalProperties: false, required: ["overall_assessment", "findings", "recommended_disposition", "limitations"], properties: { overall_assessment: { type: "string", enum: ["complete", "needs_attention", "insufficient_evidence"] }, findings: { type: "array", maxItems: 40, items: finding }, recommended_disposition: { type: "string", enum: [...CAPA_ACTION_PLAN_REVIEW_ADVISORY_DISPOSITIONS] }, limitations: { type: "array", maxItems: 40, items: text } } }, citations: { type: "array", maxItems: 0, items: { type: "string" } }, advisory_only: { type: "boolean", const: true }, workflow_mutated: { type: "boolean", const: false }, controlled_record_mutated: { type: "boolean", const: false }, approval_claimed: { type: "boolean", const: false }, workflow_transition: { type: "null" }, human_acceptance_required: { type: "boolean", const: true } } } as const);
export type CapaActionPlanReviewAdvisoryJsonSchema = Readonly<Record<string, unknown>>;

export function buildCapaActionPlanReviewAdvisoryJsonSchema(input: { readonly authoritative_action_ids: readonly string[]; readonly authoritative_root_cause_ids: readonly string[]; readonly authoritative_reference_keys: readonly string[] }): CapaActionPlanReviewAdvisoryJsonSchema {
  const actionIds = Object.freeze([...input.authoritative_action_ids]);
  const rootCauseIds = Object.freeze([...input.authoritative_root_cause_ids]);
  const referenceKeys = Object.freeze([...input.authoritative_reference_keys]);
  const base = CAPA_ACTION_PLAN_REVIEW_ADVISORY_JSON_SCHEMA;
  const proposal = base.properties.proposal as Record<string, unknown>;
  const proposalProperties = proposal.properties as Record<string, unknown>;
  const findings = proposalProperties.findings as Record<string, unknown>;
  const findingItems = findings.items as Record<string, unknown>;
  const findingProperties = findingItems.properties as Record<string, unknown>;
  return Object.freeze({
    ...base,
    properties: {
      ...base.properties,
      proposal: {
        ...proposal,
        properties: {
          ...proposalProperties,
          findings: {
            ...findings,
            items: {
              ...findingItems,
              properties: {
                ...findingProperties,
                affected_action_ids: { type: "array", maxItems: 40, items: { type: "string", enum: actionIds } },
                affected_root_cause_ids: { type: "array", maxItems: 40, items: { type: "string", enum: rootCauseIds } },
                reference_keys: { type: "array", maxItems: 40, items: { type: "string", enum: referenceKeys } },
              },
            },
          },
        },
      },
    },
  });
}

export function buildCapaActionPlanReviewAdvisoryPrompt(input: { readonly model_safe_context: unknown }): string { return ["You are AG-REVIEW, the governed CAPA S70 Action Plan Review advisory assistant.", "You are advisory only. The human reviewer retains exclusive authority to approve or return the action plan. Never execute, claim, or imply a workflow transition, human review decision, implementation, effectiveness conclusion, regulatory determination, owner assignment, or record mutation.", "Analyze only the authoritative submitted S70 baseline supplied below. Report missing evidence rather than inventing owners, dates, root causes, actions, requirements, or citations. Use only the supplied R# references. Recommendations are suggestions for human review, not decisions.", "For affected_action_ids, use only the exact authoritative action item_id values supplied in action_plan.items. For affected_root_cause_ids, use only the exact authoritative hypothesis_id values supplied in root_cause_package.hypotheses. For reference_keys, use only the supplied authoritative R# keys. Never invent identifiers, substitute display labels, or substitute another identifier field. If a finding cannot be tied to a supplied authoritative action or root cause, use an empty array for that field.", "BEGIN AUTHORITATIVE_S70_CONTEXT", JSON.stringify(input.model_safe_context), "END AUTHORITATIVE_S70_CONTEXT", `Return only JSON matching ${CAPA_ACTION_PLAN_REVIEW_ADVISORY_OUTPUT_SCHEMA_VERSION}. Evaluate root-cause coverage, action quality and specificity, ownership, dates, dependencies, deliverables, implementation evidence, unintended consequences, effectiveness checks, acceptance criteria, regulatory/quality linkage, duplicates/conflicts, rationale, and completeness. Set advisory_only=true, workflow_mutated=false, controlled_record_mutated=false, approval_claimed=false, workflow_transition=null, human_acceptance_required=true, citations=[].`].join("\n\n"); }

export interface CapaActionPlanReviewAdvisoryStructuredModelClient { generateStructured(input: { readonly prompt: string; readonly model_profile_version: typeof CAPA_ACTION_PLAN_REVIEW_ADVISORY_MODEL_PROFILE.profile_version; readonly output_schema_name: typeof CAPA_ACTION_PLAN_REVIEW_ADVISORY_MODEL_PROFILE.output_schema_name; readonly output_schema: CapaActionPlanReviewAdvisoryJsonSchema; readonly maximum_output_characters: typeof CAPA_ACTION_PLAN_REVIEW_ADVISORY_MODEL_PROFILE.maximum_output_characters; readonly store: false }): Promise<{ readonly output_text: string }>; }
export interface CapaActionPlanReviewAdvisoryGenerationTraceCapture { readonly trace_schema_version: typeof CAPA_AI_GENERATION_TRACE_SCHEMA_VERSION; readonly package: Readonly<Record<string, unknown>>; readonly rendered_prompt: string; readonly model_profile_version: string; readonly output_schema_name: string; readonly output_schema: unknown; readonly store: false; readonly maximum_output_characters: number; readonly evidence_manifest: Readonly<Record<string, unknown>>; readonly policy_manifest: Readonly<Record<string, unknown>>; readonly fingerprints: Readonly<Record<string, string>> & { readonly algorithm: typeof CAPA_AI_GENERATION_FINGERPRINT_ALGORITHM }; }
function createTrace(input: { readonly rendered_prompt: string; readonly model_profile_version: string; readonly output_schema_name: string; readonly output_schema: unknown; readonly maximum_output_characters: number; readonly run_id: CapaAiRunId; readonly prompt_package_id: CapaPromptPackageId; readonly request_id: RequestId; readonly correlation_id: CorrelationId; readonly assembled_at: IsoDateTime; readonly context: CapaActionPlanReviewAdvisoryContextAssembly }): CapaActionPlanReviewAdvisoryGenerationTraceCapture {
  const schema = snapshotCapaAiGenerationTraceValue(input.output_schema); const schemaHash = fingerprintCanonicalJson(schema); const governance = { advisory_only: true, workflow_mutated: false, controlled_record_mutated: false, human_acceptance_required: true } as const;
  const pkg = snapshotCapaAiGenerationTraceValue({ package_schema_version: "capa-action-plan-review-advisory-prompt-package-1.0.0", scope: { organization_id: input.context.authoritative.organization_id, capa_case_id: input.context.authoritative.capa_case_id, case_version_id: input.context.authoritative.case_version_id, record_version: input.context.authoritative.record_version, workflow_state: "S70" }, agent: { agent_id: "AG-REVIEW", agent_version: "ag-review-1.0.0" }, trace: { run_id: input.run_id, prompt_package_id: input.prompt_package_id, request_id: input.request_id, correlation_id: input.correlation_id, assembled_at: input.assembled_at }, generation_contract: { operation: "assemble_review_packet", requested_output: CAPA_ACTION_PLAN_REVIEW_ADVISORY_OUTPUT, output_schema_version: CAPA_ACTION_PLAN_REVIEW_ADVISORY_OUTPUT_SCHEMA_VERSION, model_profile_version: input.model_profile_version, output_schema_name: input.output_schema_name, output_schema_sha256: schemaHash, store: false, maximum_output_characters: input.maximum_output_characters }, context_provenance: { model_safe_context: input.context.model_safe_context }, governance });
  const evidence = { evidence_manifest_schema_version: "capa-action-plan-review-advisory-evidence-manifest-1.0.0", retrieval_performed: false, item_count: 0, items: [] };
  const policy = { policy_manifest_schema_version: "capa-action-plan-review-advisory-policy-manifest-1.0.0", agent: { agent_id: "AG-REVIEW", agent_version: "ag-review-1.0.0" }, workflow_state: "S70", operation: "assemble_review_packet", requested_output: CAPA_ACTION_PLAN_REVIEW_ADVISORY_OUTPUT, output_schema_version: CAPA_ACTION_PLAN_REVIEW_ADVISORY_OUTPUT_SCHEMA_VERSION, generation: { model_profile_version: input.model_profile_version, output_schema_name: input.output_schema_name, output_schema_sha256: schemaHash }, authority: governance, prohibitions: ["approval", "return decision", "workflow advancement", "controlled-record mutation", "implementation claim", "effectiveness claim"] };
  const frozenEvidence = deepFreezeCapaAiGenerationTraceValue(snapshotCapaAiGenerationTraceValue(evidence)); const frozenPolicy = deepFreezeCapaAiGenerationTraceValue(snapshotCapaAiGenerationTraceValue(policy));
  return deepFreezeCapaAiGenerationTraceValue({ trace_schema_version: CAPA_AI_GENERATION_TRACE_SCHEMA_VERSION, package: deepFreezeCapaAiGenerationTraceValue(pkg), rendered_prompt: input.rendered_prompt, model_profile_version: input.model_profile_version, output_schema_name: input.output_schema_name, output_schema: deepFreezeCapaAiGenerationTraceValue(schema), store: false, maximum_output_characters: input.maximum_output_characters, evidence_manifest: frozenEvidence, policy_manifest: frozenPolicy, fingerprints: { algorithm: CAPA_AI_GENERATION_FINGERPRINT_ALGORITHM, prompt_package_sha256: fingerprintCanonicalJson(pkg), rendered_prompt_sha256: sha256Utf8(input.rendered_prompt), evidence_manifest_sha256: fingerprintCanonicalJson(frozenEvidence), policy_manifest_sha256: fingerprintCanonicalJson(frozenPolicy), output_schema_sha256: schemaHash } }) as CapaActionPlanReviewAdvisoryGenerationTraceCapture;
}
export interface CapaActionPlanReviewAdvisoryModelGeneratorDependencies { readonly model_client: CapaActionPlanReviewAdvisoryStructuredModelClient; readonly createRunId: () => CapaAiRunId; readonly createPromptPackageId: () => CapaPromptPackageId; readonly createOutputId: () => CapaAiOutputId; readonly now: () => IsoDateTime; }
export class CapaActionPlanReviewAdvisoryModelGenerator {
  constructor(private readonly dependencies: CapaActionPlanReviewAdvisoryModelGeneratorDependencies) {}
  async generate(input: { readonly context: CapaActionPlanReviewAdvisoryContextAssembly; readonly request_id: RequestId; readonly correlation_id: CorrelationId }): Promise<{ readonly response: CapaActionPlanReviewAdvisoryResponse; readonly trace: CapaActionPlanReviewAdvisoryGenerationTraceCapture }> {
    const run_id = this.dependencies.createRunId(); const prompt_package_id = this.dependencies.createPromptPackageId(); const output_id = this.dependencies.createOutputId(); const assembled_at = this.dependencies.now(); const prompt = buildCapaActionPlanReviewAdvisoryPrompt({ model_safe_context: input.context.model_safe_context }); const output_schema = buildCapaActionPlanReviewAdvisoryJsonSchema({ authoritative_action_ids: input.context.authoritative.sections.action_plan.content.items.map((item) => item.item_id), authoritative_root_cause_ids: input.context.authoritative.sections.root_cause_package.content.hypotheses.map((hypothesis) => hypothesis.hypothesis_id), authoritative_reference_keys: input.context.reference_manifest.map((reference) => reference.reference_key) }); const trace = createTrace({ rendered_prompt: prompt, model_profile_version: CAPA_ACTION_PLAN_REVIEW_ADVISORY_MODEL_PROFILE.profile_version, output_schema_name: CAPA_ACTION_PLAN_REVIEW_ADVISORY_MODEL_PROFILE.output_schema_name, output_schema, maximum_output_characters: CAPA_ACTION_PLAN_REVIEW_ADVISORY_MODEL_PROFILE.maximum_output_characters, run_id, prompt_package_id, request_id: input.request_id, correlation_id: input.correlation_id, assembled_at, context: input.context });
    const result = await this.dependencies.model_client.generateStructured({ prompt, model_profile_version: CAPA_ACTION_PLAN_REVIEW_ADVISORY_MODEL_PROFILE.profile_version, output_schema_name: CAPA_ACTION_PLAN_REVIEW_ADVISORY_MODEL_PROFILE.output_schema_name, output_schema, maximum_output_characters: CAPA_ACTION_PLAN_REVIEW_ADVISORY_MODEL_PROFILE.maximum_output_characters, store: false }); const raw = validateCapaActionPlanReviewAdvisoryModelOutput(result.output_text); const response = Object.freeze({ ...raw, run_id, output_id, output_schema_version: CAPA_ACTION_PLAN_REVIEW_ADVISORY_OUTPUT_SCHEMA_VERSION as never }); return { response, trace };
  }
}
