import { randomUUID } from "node:crypto";
import type { CapaKnowledgeRetrievalService } from "../knowledge/capa-knowledge-retrieval-service";
import { isCapaKnowledgeRetrievalUsable } from "../knowledge/capa-knowledge-retrieval-contract";
import type { CapaIntakeAdvisoryRetrievalConfiguration } from "./capa-intake-advisory-retrieval-request-factory";
import type { CapaImplementationEvidenceAdvisoryKnowledgeProvider } from "./capa-implementation-evidence-advisory-context";
import type { CapaKnowledgeRetrievalQueryId, CapaKnowledgeRetrievalRunId } from "../knowledge/capa-knowledge-retrieval-contract";

/**
 * Reuses the existing current-effective CAPA knowledge retrieval boundary.
 * Configuration is server-owned; browser input cannot select a collection,
 * source version, policy, or retrieval method.
 */
export class GovernedCapaImplementationEvidenceAdvisoryKnowledgeProvider implements CapaImplementationEvidenceAdvisoryKnowledgeProvider {
  constructor(private readonly retrieval_service: CapaKnowledgeRetrievalService, private readonly configuration: CapaIntakeAdvisoryRetrievalConfiguration, private readonly now: () => Date) {}
  async retrieve(input: Parameters<CapaImplementationEvidenceAdvisoryKnowledgeProvider["retrieve"]>[0]): Promise<Awaited<ReturnType<CapaImplementationEvidenceAdvisoryKnowledgeProvider["retrieve"]>>> {
    const timestamp = this.now();
    if (!Number.isFinite(timestamp.getTime())) throw new Error("INVALID_KNOWLEDGE_RETRIEVAL_TIME");
    const result = await this.retrieval_service.retrieve({ request: { retrieval_run_id: randomUUID() as CapaKnowledgeRetrievalRunId, query_id: randomUUID() as CapaKnowledgeRetrievalQueryId, request_trace: { request_id: input.request_id, correlation_id: input.correlation_id }, scope: { organization_id: input.organization_id, actor: { actor_type: "human", actor_id: input.user_id }, active_role_ids: input.active_roles.map((role) => role.role_id), permitted_site_ids: [], permitted_product_ids: [], collection_id: this.configuration.collection_id, collection_version_id: this.configuration.collection_version_id, approved_global_sources_permitted: false }, task_type: "CAPA_SUPPORT" as never, filters: { effective_at: timestamp.toISOString() as never, historical_source_versions_permitted: false }, policy: { retrieval_policy_version: this.configuration.retrieval_policy_version as never, source_precedence_policy_version: this.configuration.source_precedence_policy_version as never, query_construction_version: this.configuration.query_construction_version as never, ranking_policy_version: this.configuration.ranking_policy_version as never, citation_policy_version: this.configuration.citation_policy_version as never, retrieval_method: "lexical", maximum_candidates: 20, maximum_results: 8, maximum_total_characters: 20_000, minimum_relevance_score: 0.01 }, requested_at: timestamp.toISOString() as never }, query: { user_query: "CAPA implementation evidence and approved action alignment", task_type: "CAPA_SUPPORT" as never, workflow_state: "S80" as never, authorized_context: [] } });
    const evidence = result.evidence_package;
    if (!isCapaKnowledgeRetrievalUsable(evidence.outcome)) return { references: [], citations: [], warnings: [...evidence.warnings, `Governed retrieval returned ${evidence.outcome}: ${evidence.reason_code}.`], retrieval_provenance: { retrieval_run_id: evidence.retrieval_run_id, collection_id: result.request.scope.collection_id, collection_version_id: evidence.collection_version_id, retrieval_policy_version: result.request.policy.retrieval_policy_version, source_precedence_policy_version: result.request.policy.source_precedence_policy_version, query_construction_version: result.request.policy.query_construction_version, ranking_policy_version: result.request.policy.ranking_policy_version, citation_policy_version: result.request.policy.citation_policy_version } };
    return { references: evidence.passages.map((passage) => ({ source_reference: passage.source_id, source_id: passage.source_id, source_version_id: passage.source_version_id, passage_id: passage.passage_id, title: passage.title, locator: passage.locators.join(", "), source_status: passage.source_status_at_use, relationship: passage.relationship, text: { trust: "untrusted_data", provenance_type: "retrieved_passage", content: passage.content } })), citations: [], warnings: [...evidence.warnings], retrieval_provenance: { retrieval_run_id: evidence.retrieval_run_id, collection_id: result.request.scope.collection_id, collection_version_id: evidence.collection_version_id, retrieval_policy_version: result.request.policy.retrieval_policy_version, source_precedence_policy_version: result.request.policy.source_precedence_policy_version, query_construction_version: result.request.policy.query_construction_version, ranking_policy_version: result.request.policy.ranking_policy_version, citation_policy_version: result.request.policy.citation_policy_version } };
  }
}
