import type { RawCapaContainmentRiskAdvisoryModelOutput } from "./capa-containment-risk-advisory-contract";
import { validateCapaContainmentRiskAdvisoryModelOutput } from "./capa-containment-risk-advisory-output-validator";
import type { CapaContainmentRiskAdvisoryContextAssembly } from "./capa-containment-risk-advisory-context";
import { buildCapaContainmentRiskAdvisoryPrompt } from "./capa-containment-risk-advisory-prompt";
import { CAPA_CONTAINMENT_RISK_ADVISORY_EVIDENCE_GAP_CATEGORIES, CAPA_CONTAINMENT_RISK_ADVISORY_IMPACT_DIMENSIONS, CAPA_CONTAINMENT_RISK_ADVISORY_RISK_INPUT_TOPICS, CAPA_CONTAINMENT_RISK_ADVISORY_ASSUMPTION_AREAS, CAPA_CONTAINMENT_RISK_ADVISORY_UNCERTAINTY_CATEGORIES } from "./capa-containment-risk-advisory-contract";

export const CAPA_CONTAINMENT_RISK_ADVISORY_MODEL_PROFILE = Object.freeze({ profile_version: "capa-model-profile-1.0.0" as const, output_schema_name: "capa_containment_risk_advisory_1_0_0" as const, maximum_output_characters: 30_000 });
const question = { type: "string" } as const;
export const CAPA_CONTAINMENT_RISK_ADVISORY_JSON_SCHEMA = Object.freeze({ type: "object", additionalProperties: false, required: ["proposal", "assumptions", "uncertainty_and_limitations", "citations", "advisory_only", "workflow_mutated", "human_acceptance_required"], properties: { proposal: { type: "object", additionalProperties: false, required: ["missing_risk_inputs", "missing_impact_dimensions", "human_review_questions", "evidence_provenance_gaps"], properties: { missing_risk_inputs: { type: "array", items: { type: "object", additionalProperties: false, required: ["topic", "human_review_question"], properties: { topic: { type: "string", enum: [...CAPA_CONTAINMENT_RISK_ADVISORY_RISK_INPUT_TOPICS] }, human_review_question: question } } }, missing_impact_dimensions: { type: "array", items: { type: "object", additionalProperties: false, required: ["dimension", "human_review_question"], properties: { dimension: { type: "string", enum: [...CAPA_CONTAINMENT_RISK_ADVISORY_IMPACT_DIMENSIONS] }, human_review_question: question } } }, human_review_questions: { type: "array", items: question }, evidence_provenance_gaps: { type: "array", items: { type: "object", additionalProperties: false, required: ["category", "human_review_question"], properties: { category: { type: "string", enum: [...CAPA_CONTAINMENT_RISK_ADVISORY_EVIDENCE_GAP_CATEGORIES] }, human_review_question: question } } } } }, assumptions: { type: "array", items: { type: "object", additionalProperties: false, required: ["unverified", "related_area", "verification_question"], properties: { unverified: { const: true }, related_area: { type: "string", enum: [...CAPA_CONTAINMENT_RISK_ADVISORY_ASSUMPTION_AREAS] }, verification_question: question } } }, uncertainty_and_limitations: { type: "array", items: { type: "object", additionalProperties: false, required: ["category", "human_review_question"], properties: { category: { type: "string", enum: [...CAPA_CONTAINMENT_RISK_ADVISORY_UNCERTAINTY_CATEGORIES] }, human_review_question: question } } }, citations: { type: "array", maxItems: 0, items: {} }, advisory_only: { const: true }, workflow_mutated: { const: false }, human_acceptance_required: { const: true } } } as const);
export interface CapaContainmentRiskAdvisoryStructuredModelClient { generateStructured(input: { readonly prompt: string; readonly model_profile_version: typeof CAPA_CONTAINMENT_RISK_ADVISORY_MODEL_PROFILE.profile_version; readonly output_schema_name: typeof CAPA_CONTAINMENT_RISK_ADVISORY_MODEL_PROFILE.output_schema_name; readonly output_schema: typeof CAPA_CONTAINMENT_RISK_ADVISORY_JSON_SCHEMA; readonly maximum_output_characters: number; readonly store: false }): Promise<{ readonly output_text: string }>; }
export interface CapaContainmentRiskAdvisoryGenerationInput { readonly context: CapaContainmentRiskAdvisoryContextAssembly; readonly focus?: string | null; }
export interface CapaContainmentRiskAdvisoryModelGeneratorDependencies { readonly model_client: CapaContainmentRiskAdvisoryStructuredModelClient; }
export class CapaContainmentRiskAdvisoryModelGenerator {
  constructor(private readonly dependencies: CapaContainmentRiskAdvisoryModelGeneratorDependencies) {}
  async generate(input: CapaContainmentRiskAdvisoryGenerationInput): Promise<RawCapaContainmentRiskAdvisoryModelOutput> {
    const prompt = buildCapaContainmentRiskAdvisoryPrompt(input);
    if (typeof prompt !== "string" || prompt.trim().length === 0 || prompt.length > 120_000) throw new Error("CONTROLLED_CAPA_PROMPT_INVALID");
    const raw = await this.dependencies.model_client.generateStructured({ prompt, model_profile_version: CAPA_CONTAINMENT_RISK_ADVISORY_MODEL_PROFILE.profile_version, output_schema_name: CAPA_CONTAINMENT_RISK_ADVISORY_MODEL_PROFILE.output_schema_name, output_schema: CAPA_CONTAINMENT_RISK_ADVISORY_JSON_SCHEMA, maximum_output_characters: CAPA_CONTAINMENT_RISK_ADVISORY_MODEL_PROFILE.maximum_output_characters, store: false });
    return validateCapaContainmentRiskAdvisoryModelOutput(raw.output_text);
  }
}
