import type { CapaCaseId, CapaCaseVersionId, CorrelationId, OrganizationId, RequestId, UserId } from "../domain/capa-types";
import type { TransactionManager } from "../../database/transactions";
import type { CapaActionPlanAdvisoryContextAssembly, AuthoritativeS60ActionPlanContext, CapaActionPlanAdvisoryContextResolution } from "./capa-action-plan-advisory-context";
import { CAPA_ACTION_PLAN_ADVISORY_AGENT, type CapaActionPlanAdvisoryAgentGate } from "./capa-action-plan-advisory-agent-gate";
import { CAPA_ACTION_PLAN_ADVISORY_OPERATION } from "./capa-action-plan-advisory-model-generator";
import { CAPA_ACTION_PLAN_ADVISORY_OUTPUT_SCHEMA_VERSION, type CapaActionPlanAdvisoryResponse } from "./capa-action-plan-advisory-contract";
import type { CapaActionPlanAdvisoryGenerationTraceCapture } from "./capa-ai-generation-trace";
import { CapaActionPlanAdvisoryOutputValidationError } from "./capa-action-plan-advisory-validator";
import type { CapaActionPlanAdvisoryOutputRepository } from "../../database/repositories/capa-action-plan-advisory-output-repository";

export const CAPA_ACTION_PLAN_ADVISORY_SERVICE_REASON_CODES = ["CASE_NOT_FOUND_OR_NOT_AUTHORIZED", "CASE_NOT_IN_ACTION_PLANNING", "ADVISORY_ACCESS_DENIED", "AGENT_NOT_ELIGIBLE", "ADVISORY_GENERATION_FAILED", "INVALID_ADVISORY_RESULT", "ADVISORY_PERSISTENCE_FAILED", "WORKFLOW_MUTATION_DETECTED"] as const;
export type CapaActionPlanAdvisoryServiceReasonCode = typeof CAPA_ACTION_PLAN_ADVISORY_SERVICE_REASON_CODES[number];
export class CapaActionPlanAdvisoryServiceError extends Error { constructor(readonly reason_code: CapaActionPlanAdvisoryServiceReasonCode, readonly diagnostic_cause_name?: string) { super("The governed S60 action-plan advisory operation failed."); this.name = "CapaActionPlanAdvisoryServiceError"; } }
export interface CapaActionPlanAdvisoryInvocation { readonly organization_id: OrganizationId; readonly capa_case_id: CapaCaseId; readonly user_id: UserId; readonly request_id: RequestId; readonly correlation_id: CorrelationId; readonly request: { readonly expected_case_version_id: CapaCaseVersionId; readonly expected_record_version: number } }
export interface CapaActionPlanAdvisoryContextResolver { resolve(input: { readonly organization_id: OrganizationId; readonly capa_case_id: CapaCaseId }): Promise<CapaActionPlanAdvisoryContextResolution>; assertCaseUnchanged(context: AuthoritativeS60ActionPlanContext): Promise<boolean>; }
export interface CapaActionPlanAdvisoryAuthorizer { authorize(input: { readonly context: AuthoritativeS60ActionPlanContext; readonly operation: typeof CAPA_ACTION_PLAN_ADVISORY_OPERATION }): Promise<boolean>; }
export interface CapaActionPlanAdvisoryGenerator { generate(input: { readonly context: CapaActionPlanAdvisoryContextAssembly; readonly request_id: RequestId; readonly correlation_id: CorrelationId }): Promise<{ readonly response: CapaActionPlanAdvisoryResponse; readonly trace: CapaActionPlanAdvisoryGenerationTraceCapture }>; }
export interface CapaActionPlanAdvisoryServiceDependencies { readonly context_resolver: CapaActionPlanAdvisoryContextResolver; readonly authorizer: CapaActionPlanAdvisoryAuthorizer; readonly agent_gate: CapaActionPlanAdvisoryAgentGate; readonly generator: CapaActionPlanAdvisoryGenerator; readonly output_repository: CapaActionPlanAdvisoryOutputRepository; readonly transaction_manager: TransactionManager; }
function record(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
function validContext(value: unknown, invocation: CapaActionPlanAdvisoryInvocation): value is AuthoritativeS60ActionPlanContext { return record(value) && value.trust === "authoritative_server_context" && value.organization_id === invocation.organization_id && value.capa_case_id === invocation.capa_case_id && value.actor === invocation.user_id && value.workflow_state === "S60" && value.case_version_id === invocation.request.expected_case_version_id && value.record_version === invocation.request.expected_record_version && Array.isArray(value.active_roles); }
function validGenerated(value: unknown, context: AuthoritativeS60ActionPlanContext, invocation: CapaActionPlanAdvisoryInvocation): value is { response: CapaActionPlanAdvisoryResponse; trace: CapaActionPlanAdvisoryGenerationTraceCapture } { if (!record(value) || !record(value.response) || !record(value.trace)) return false; const response = value.response; const trace = value.trace; const pkg = record(trace.package) ? trace.package : null; const scope = pkg && record(pkg.scope) ? pkg.scope : null; const identity = pkg && record(pkg.trace) ? pkg.trace : null; return response.status === "completed_draft" && response.output_schema_version === CAPA_ACTION_PLAN_ADVISORY_OUTPUT_SCHEMA_VERSION && response.advisory_only === true && response.workflow_mutated === false && response.controlled_record_mutated === false && response.approval_claimed === false && response.workflow_transition === null && response.human_acceptance_required === true && trace.trace_schema_version === "capa-ai-generation-trace-1.0.0" && pkg?.package_schema_version === "capa-action-plan-advisory-prompt-package-1.0.0" && scope?.organization_id === context.organization_id && scope?.capa_case_id === context.capa_case_id && scope?.case_version_id === context.case_version_id && scope?.record_version === context.record_version && scope?.workflow_state === "S60" && identity?.run_id === response.run_id && identity?.request_id === invocation.request_id && identity?.correlation_id === invocation.correlation_id; }

export class CapaActionPlanAdvisoryService {
  constructor(private readonly dependencies: CapaActionPlanAdvisoryServiceDependencies) {}
  async execute(invocation: CapaActionPlanAdvisoryInvocation): Promise<{ readonly advisory: CapaActionPlanAdvisoryResponse; readonly snapshot: Readonly<{ capa_case_id: CapaCaseId; case_version_id: CapaCaseVersionId; record_version: number }> }> {
    let resolution: CapaActionPlanAdvisoryContextResolution; try { resolution = await this.dependencies.context_resolver.resolve({ organization_id: invocation.organization_id, capa_case_id: invocation.capa_case_id }); } catch { throw new CapaActionPlanAdvisoryServiceError("CASE_NOT_FOUND_OR_NOT_AUTHORIZED"); }
    if (resolution.status === "not_found_or_not_authorized" || resolution.status === "invalid_authoritative_context") throw new CapaActionPlanAdvisoryServiceError("CASE_NOT_FOUND_OR_NOT_AUTHORIZED");
    if (resolution.status === "wrong_workflow_state") throw new CapaActionPlanAdvisoryServiceError("CASE_NOT_IN_ACTION_PLANNING");
    const context = resolution.assembly.authoritative; if (!validContext(context, invocation)) throw new CapaActionPlanAdvisoryServiceError("CASE_NOT_FOUND_OR_NOT_AUTHORIZED");
    let authorized = false; try { authorized = await this.dependencies.authorizer.authorize({ context, operation: CAPA_ACTION_PLAN_ADVISORY_OPERATION }); } catch { authorized = false; } if (!authorized) throw new CapaActionPlanAdvisoryServiceError("ADVISORY_ACCESS_DENIED");
    let eligible = false; try { eligible = this.dependencies.agent_gate.evaluate({ context, agent: CAPA_ACTION_PLAN_ADVISORY_AGENT, operation: CAPA_ACTION_PLAN_ADVISORY_OPERATION }); } catch { eligible = false; } if (!eligible) throw new CapaActionPlanAdvisoryServiceError("AGENT_NOT_ELIGIBLE");
    let generated: Awaited<ReturnType<CapaActionPlanAdvisoryGenerator["generate"]>>; try { generated = await this.dependencies.generator.generate({ context: resolution.assembly, request_id: invocation.request_id, correlation_id: invocation.correlation_id }); } catch (error) { throw new CapaActionPlanAdvisoryServiceError("ADVISORY_GENERATION_FAILED", error instanceof Error ? error.name : "UnknownError"); }
    if (!validGenerated(generated, context, invocation)) throw new CapaActionPlanAdvisoryServiceError("INVALID_ADVISORY_RESULT");
    let unchanged = false; try { unchanged = await this.dependencies.context_resolver.assertCaseUnchanged(context); } catch { unchanged = false; } if (!unchanged) throw new CapaActionPlanAdvisoryServiceError("WORKFLOW_MUTATION_DETECTED");
    try { const saved = await this.dependencies.transaction_manager.runInTransaction({ request_id: invocation.request_id, correlation_id: invocation.correlation_id }, (transaction) => this.dependencies.output_repository.save(transaction, { context, response: generated.response, generation_trace: generated.trace, reference_manifest: resolution.assembly.reference_manifest, request_id: invocation.request_id, correlation_id: invocation.correlation_id })); if (saved === "case_changed") throw new CapaActionPlanAdvisoryServiceError("WORKFLOW_MUTATION_DETECTED"); } catch (error) { if (error instanceof CapaActionPlanAdvisoryServiceError) throw error; throw new CapaActionPlanAdvisoryServiceError("ADVISORY_PERSISTENCE_FAILED", error instanceof Error ? error.name : "UnknownError"); }
    return { advisory: generated.response, snapshot: { capa_case_id: context.capa_case_id, case_version_id: context.case_version_id, record_version: context.record_version } };
  }
}
