import type { CapaCaseId, CapaCaseVersionId, CorrelationId, OrganizationId, RequestId, UserId } from "../domain/capa-types";
import type { TransactionManager } from "../../database/transactions";
import type { AuthoritativeS70ActionPlanReviewContext, CapaActionPlanReviewAdvisoryContextAssembly, CapaActionPlanReviewAdvisoryContextResolution } from "./capa-action-plan-review-advisory-context";
import { CAPA_ACTION_PLAN_REVIEW_ADVISORY_AGENT, CAPA_ACTION_PLAN_REVIEW_ADVISORY_OPERATION, type CapaActionPlanReviewAdvisoryAgentGate } from "./capa-action-plan-review-advisory-agent-gate";
import { CAPA_ACTION_PLAN_REVIEW_ADVISORY_OUTPUT_SCHEMA_VERSION, type CapaActionPlanReviewAdvisoryResponse } from "./capa-action-plan-review-advisory-contract";
import type { CapaActionPlanReviewAdvisoryGenerationTraceCapture } from "./capa-action-plan-review-advisory-model-generator";
import type { CapaActionPlanReviewAdvisoryOutputRepository } from "../../database/repositories/capa-action-plan-review-advisory-output-repository";

export const CAPA_ACTION_PLAN_REVIEW_ADVISORY_SERVICE_REASON_CODES = ["CASE_NOT_FOUND_OR_NOT_AUTHORIZED", "CASE_NOT_IN_ACTION_PLAN_REVIEW", "ADVISORY_ACCESS_DENIED", "AGENT_NOT_ELIGIBLE", "ADVISORY_GENERATION_FAILED", "INVALID_ADVISORY_RESULT", "ADVISORY_PERSISTENCE_FAILED", "WORKFLOW_MUTATION_DETECTED"] as const;
export type CapaActionPlanReviewAdvisoryServiceReasonCode = typeof CAPA_ACTION_PLAN_REVIEW_ADVISORY_SERVICE_REASON_CODES[number];
export class CapaActionPlanReviewAdvisoryServiceError extends Error { constructor(readonly reason_code: CapaActionPlanReviewAdvisoryServiceReasonCode, readonly diagnostic_cause_name?: string) { super("The governed CAPA S70 action-plan review advisory operation failed."); this.name = "CapaActionPlanReviewAdvisoryServiceError"; } }
export interface CapaActionPlanReviewAdvisoryInvocation { readonly organization_id: OrganizationId; readonly capa_case_id: CapaCaseId; readonly user_id: UserId; readonly request_id: RequestId; readonly correlation_id: CorrelationId; readonly request: { readonly expected_case_version_id: CapaCaseVersionId; readonly expected_record_version: number } }
export interface CapaActionPlanReviewAdvisoryContextResolver { resolve(input: { readonly organization_id: OrganizationId; readonly capa_case_id: CapaCaseId }): Promise<CapaActionPlanReviewAdvisoryContextResolution>; assertCaseUnchanged(context: AuthoritativeS70ActionPlanReviewContext): Promise<boolean>; }
export interface CapaActionPlanReviewAdvisoryAuthorizer { authorize(input: { readonly context: AuthoritativeS70ActionPlanReviewContext; readonly operation: typeof CAPA_ACTION_PLAN_REVIEW_ADVISORY_OPERATION }): Promise<boolean>; }
export interface CapaActionPlanReviewAdvisoryGenerator { generate(input: { readonly context: CapaActionPlanReviewAdvisoryContextAssembly; readonly request_id: RequestId; readonly correlation_id: CorrelationId }): Promise<{ readonly response: CapaActionPlanReviewAdvisoryResponse; readonly trace: CapaActionPlanReviewAdvisoryGenerationTraceCapture }>; }
export interface CapaActionPlanReviewAdvisoryServiceDependencies { readonly context_resolver: CapaActionPlanReviewAdvisoryContextResolver; readonly authorizer: CapaActionPlanReviewAdvisoryAuthorizer; readonly agent_gate: CapaActionPlanReviewAdvisoryAgentGate; readonly generator: CapaActionPlanReviewAdvisoryGenerator; readonly output_repository: CapaActionPlanReviewAdvisoryOutputRepository; readonly transaction_manager: TransactionManager; }
function record(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
function validContext(value: unknown, invocation: CapaActionPlanReviewAdvisoryInvocation): value is AuthoritativeS70ActionPlanReviewContext { return record(value) && value.trust === "authoritative_server_context" && value.organization_id === invocation.organization_id && value.capa_case_id === invocation.capa_case_id && value.actor === invocation.user_id && value.workflow_state === "S70" && value.case_version_id === invocation.request.expected_case_version_id && value.record_version === invocation.request.expected_record_version && Array.isArray(value.active_roles); }
function validGenerated(value: unknown, context: AuthoritativeS70ActionPlanReviewContext, invocation: CapaActionPlanReviewAdvisoryInvocation, assembly: CapaActionPlanReviewAdvisoryContextAssembly): value is { response: CapaActionPlanReviewAdvisoryResponse; trace: CapaActionPlanReviewAdvisoryGenerationTraceCapture } { if (!record(value) || !record(value.response) || !record(value.trace)) return false; const response = value.response; const trace = value.trace; const pkg = record(trace.package) ? trace.package : null; const scope = pkg && record(pkg.scope) ? pkg.scope : null; const identity = pkg && record(pkg.trace) ? pkg.trace : null; const output = pkg && record(pkg.generation_contract) ? pkg.generation_contract : null; const actionIds = new Set(context.sections.action_plan.content.items.map((item) => item.item_id)); const rootIds = new Set(context.sections.root_cause_package.content.hypotheses.map((item) => item.hypothesis_id)); const referenceKeys = new Set(assembly.reference_manifest.map((item) => item.reference_key)); const findings = record(response.proposal) && Array.isArray(response.proposal.findings) ? response.proposal.findings : []; const findingBindingsValid = findings.every((finding) => record(finding) && Array.isArray(finding.affected_action_ids) && finding.affected_action_ids.every((id) => actionIds.has(id)) && Array.isArray(finding.affected_root_cause_ids) && finding.affected_root_cause_ids.every((id) => rootIds.has(id)) && Array.isArray(finding.reference_keys) && finding.reference_keys.every((key) => referenceKeys.has(key))); return response.status === "completed_draft" && response.output_schema_version === CAPA_ACTION_PLAN_REVIEW_ADVISORY_OUTPUT_SCHEMA_VERSION && response.source_case_version_id === context.case_version_id && response.action_plan_section_version_id === context.sections.action_plan.section_version_id && response.advisory_only === true && response.workflow_mutated === false && response.controlled_record_mutated === false && response.approval_claimed === false && response.workflow_transition === null && response.human_acceptance_required === true && findingBindingsValid && pkg?.package_schema_version === "capa-action-plan-review-advisory-prompt-package-1.0.0" && scope?.workflow_state === "S70" && scope?.organization_id === context.organization_id && scope?.capa_case_id === context.capa_case_id && scope?.case_version_id === context.case_version_id && scope?.record_version === context.record_version && identity?.run_id === response.run_id && identity?.request_id === invocation.request_id && identity?.correlation_id === invocation.correlation_id && output?.operation === CAPA_ACTION_PLAN_REVIEW_ADVISORY_OPERATION && output?.output_schema_version === CAPA_ACTION_PLAN_REVIEW_ADVISORY_OUTPUT_SCHEMA_VERSION; }
export class CapaActionPlanReviewAdvisoryService {
  constructor(private readonly dependencies: CapaActionPlanReviewAdvisoryServiceDependencies) {}
  async execute(invocation: CapaActionPlanReviewAdvisoryInvocation): Promise<{ readonly advisory: CapaActionPlanReviewAdvisoryResponse; readonly snapshot: Readonly<{ capa_case_id: CapaCaseId; case_version_id: CapaCaseVersionId; record_version: number }> }> {
    let resolution: CapaActionPlanReviewAdvisoryContextResolution; try { resolution = await this.dependencies.context_resolver.resolve({ organization_id: invocation.organization_id, capa_case_id: invocation.capa_case_id }); } catch { throw new CapaActionPlanReviewAdvisoryServiceError("CASE_NOT_FOUND_OR_NOT_AUTHORIZED"); }
    if (resolution.status === "not_found_or_not_authorized" || resolution.status === "invalid_authoritative_context") throw new CapaActionPlanReviewAdvisoryServiceError("CASE_NOT_FOUND_OR_NOT_AUTHORIZED"); if (resolution.status === "wrong_workflow_state") throw new CapaActionPlanReviewAdvisoryServiceError("CASE_NOT_IN_ACTION_PLAN_REVIEW"); const context = resolution.assembly.authoritative; if (!validContext(context, invocation)) throw new CapaActionPlanReviewAdvisoryServiceError("CASE_NOT_FOUND_OR_NOT_AUTHORIZED");
    let authorized = false; try { authorized = await this.dependencies.authorizer.authorize({ context, operation: CAPA_ACTION_PLAN_REVIEW_ADVISORY_OPERATION }); } catch { authorized = false; } if (!authorized) throw new CapaActionPlanReviewAdvisoryServiceError("ADVISORY_ACCESS_DENIED");
    let eligible = false; try { eligible = this.dependencies.agent_gate.evaluate({ context, agent: CAPA_ACTION_PLAN_REVIEW_ADVISORY_AGENT, operation: CAPA_ACTION_PLAN_REVIEW_ADVISORY_OPERATION }); } catch { eligible = false; } if (!eligible) throw new CapaActionPlanReviewAdvisoryServiceError("AGENT_NOT_ELIGIBLE");
    let generated: Awaited<ReturnType<CapaActionPlanReviewAdvisoryGenerator["generate"]>>; try { generated = await this.dependencies.generator.generate({ context: resolution.assembly, request_id: invocation.request_id, correlation_id: invocation.correlation_id }); } catch (error) { throw new CapaActionPlanReviewAdvisoryServiceError("ADVISORY_GENERATION_FAILED", error instanceof Error ? error.name : "UnknownError"); }
    if (!validGenerated(generated, context, invocation, resolution.assembly)) throw new CapaActionPlanReviewAdvisoryServiceError("INVALID_ADVISORY_RESULT"); let unchanged = false; try { unchanged = await this.dependencies.context_resolver.assertCaseUnchanged(context); } catch { unchanged = false; } if (!unchanged) throw new CapaActionPlanReviewAdvisoryServiceError("WORKFLOW_MUTATION_DETECTED");
    try { const saved = await this.dependencies.transaction_manager.runInTransaction({ request_id: invocation.request_id, correlation_id: invocation.correlation_id }, (transaction) => this.dependencies.output_repository.save(transaction, { context, response: generated.response, generation_trace: generated.trace, reference_manifest: resolution.assembly.reference_manifest, request_id: invocation.request_id, correlation_id: invocation.correlation_id })); if (saved === "case_changed") throw new CapaActionPlanReviewAdvisoryServiceError("WORKFLOW_MUTATION_DETECTED"); } catch (error) { if (error instanceof CapaActionPlanReviewAdvisoryServiceError) throw error; throw new CapaActionPlanReviewAdvisoryServiceError("ADVISORY_PERSISTENCE_FAILED", error instanceof Error ? error.name : "UnknownError"); }
    return { advisory: generated.response, snapshot: { capa_case_id: context.capa_case_id, case_version_id: context.case_version_id, record_version: context.record_version } };
  }
}
