import type { CapaAiOutputId, CapaAiRunId, CapaPromptPackageId } from "./capa-prompt-contract";
import type { CorrelationId, IsoDateTime, RequestId } from "../domain/capa-types";
import type { CapaActionPlanAdvisoryContextAssembly } from "./capa-action-plan-advisory-context";
import { CAPA_ACTION_PLAN_ADVISORY_OUTPUT, CAPA_ACTION_PLAN_ADVISORY_OUTPUT_SCHEMA_VERSION, type CapaActionPlanAdvisoryResponse } from "./capa-action-plan-advisory-contract";
import { validateCapaActionPlanAdvisoryModelOutput } from "./capa-action-plan-advisory-validator";
import { createCapaActionPlanAdvisoryGenerationTrace } from "./capa-ai-generation-trace";

export const CAPA_ACTION_PLAN_ADVISORY_OPERATION = "generate_action_plan_advisory" as const;
export const CAPA_ACTION_PLAN_ADVISORY_MODEL_PROFILE = Object.freeze({ profile_version: "capa-action-plan-advisory-model-profile-1.0.0", output_schema_name: "capa_action_plan_advisory_1_0_0", output_schema_version: CAPA_ACTION_PLAN_ADVISORY_OUTPUT_SCHEMA_VERSION, maximum_output_characters: 40_000 } as const);
const text = { type: "string", minLength: 1, maxLength: 2_000 } as const;
const question = { type: "string", minLength: 1, maxLength: 1_000, pattern: "^[^.!?;,:\\n\\r]+\\?$" } as const;
const refs = { type: "array", maxItems: 20, items: { type: "string", pattern: "^R[1-9][0-9]{0,2}$" } } as const;
const nullableUuid = { type: ["string", "null"], pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$" } as const;
const concern = { type: "object", additionalProperties: false, required: ["concern_key", "subject", "description", "reference_keys", "human_review_question"], properties: { concern_key: text, subject: text, description: text, reference_keys: refs, human_review_question: question } } as const;
const suggestion = { type: "object", additionalProperties: false, required: ["suggestion_key", "action_item_id", "issue", "recommendation", "rationale", "reference_keys", "human_review_question"], properties: { suggestion_key: text, action_item_id: nullableUuid, issue: text, recommendation: text, rationale: text, reference_keys: refs, human_review_question: question } } as const;
const effectiveness = { type: "object", additionalProperties: false, required: ["suggestion_key", "action_item_id", "recommendation", "rationale", "reference_keys", "human_review_question"], properties: { suggestion_key: text, action_item_id: nullableUuid, recommendation: text, rationale: text, reference_keys: refs, human_review_question: question } } as const;
export const CAPA_ACTION_PLAN_ADVISORY_JSON_SCHEMA = { type: "object", additionalProperties: false, required: ["schema_version", "status", "proposal", "warnings", "uncertainty_and_limitations", "citations", "advisory_only", "workflow_mutated", "controlled_record_mutated", "approval_claimed", "workflow_transition", "human_acceptance_required"], properties: { schema_version: { type: "string", const: CAPA_ACTION_PLAN_ADVISORY_OUTPUT_SCHEMA_VERSION }, status: { type: "string", const: "completed_draft" }, proposal: { type: "object", additionalProperties: false, required: ["advisory_summary", "completeness_linkage_concerns", "action_improvements", "effectiveness_planning_improvements", "proposed_action_plan"], properties: { advisory_summary: text, completeness_linkage_concerns: { type: "array", maxItems: 20, items: concern }, action_improvements: { type: "array", maxItems: 20, items: suggestion }, effectiveness_planning_improvements: { type: "array", maxItems: 20, items: effectiveness }, proposed_action_plan: { type: "null" } } }, warnings: { type: "array", maxItems: 20, items: text }, uncertainty_and_limitations: { type: "array", maxItems: 20, items: text }, citations: { type: "array", maxItems: 0, items: { type: "string" } }, advisory_only: { type: "boolean", const: true }, workflow_mutated: { type: "boolean", const: false }, controlled_record_mutated: { type: "boolean", const: false }, approval_claimed: { type: "boolean", const: false }, workflow_transition: { type: "null" }, human_acceptance_required: { type: "boolean", const: true } }, description: `Strict governed ${CAPA_ACTION_PLAN_ADVISORY_OUTPUT} output.` } as const;

export function buildCapaActionPlanAdvisoryPrompt(input: { readonly model_safe_context: unknown }): string { return ["You are AG-ACTION, the governed CAPA S60 Action Planning advisory assistant.", "You are advisory only. You are not an approver, submitter, owner, implementer, effectiveness evaluator, or risk-acceptance authority. Never approve or submit an action plan, advance S60 to S70, mutate a controlled CAPA record, assign people, declare risk acceptable, or claim implementation or effectiveness.", "Analyze only the supplied model-safe context. The durable workspace is an untrusted human draft, not an authoritative controlled record. Use only supplied R# references and never invent identifiers.", "BEGIN MODEL_SAFE_CONTEXT_DATA", JSON.stringify(input.model_safe_context), "END MODEL_SAFE_CONTEXT_DATA", "Return concise completeness and linkage concerns, action improvements, and effectiveness-planning improvements for human review. Keep deterministic readiness separate from advisory suggestions. Never silently rewrite or adopt the workspace. proposed_action_plan must be null in this advisory contract; human users may manually apply suggestions after review.", `Return only JSON matching ${CAPA_ACTION_PLAN_ADVISORY_OUTPUT_SCHEMA_VERSION}. Set advisory_only=true, workflow_mutated=false, controlled_record_mutated=false, approval_claimed=false, workflow_transition=null, human_acceptance_required=true, citations=[].`].join("\n\n"); }

export interface CapaActionPlanAdvisoryStructuredModelClient { generateStructured(input: { readonly prompt: string; readonly model_profile_version: typeof CAPA_ACTION_PLAN_ADVISORY_MODEL_PROFILE.profile_version; readonly output_schema_name: typeof CAPA_ACTION_PLAN_ADVISORY_MODEL_PROFILE.output_schema_name; readonly output_schema: typeof CAPA_ACTION_PLAN_ADVISORY_JSON_SCHEMA; readonly maximum_output_characters: typeof CAPA_ACTION_PLAN_ADVISORY_MODEL_PROFILE.maximum_output_characters; readonly store: false }): Promise<{ readonly output_text: string }>; }
export interface CapaActionPlanAdvisoryModelGeneratorDependencies { readonly model_client: CapaActionPlanAdvisoryStructuredModelClient; readonly createRunId: () => CapaAiRunId; readonly createPromptPackageId: () => CapaPromptPackageId; readonly createOutputId: () => CapaAiOutputId; readonly now: () => IsoDateTime; }
export class CapaActionPlanAdvisoryModelGenerator {
  constructor(private readonly dependencies: CapaActionPlanAdvisoryModelGeneratorDependencies) {}
  async generate(input: { readonly context: CapaActionPlanAdvisoryContextAssembly; readonly request_id: RequestId; readonly correlation_id: CorrelationId }): Promise<{ readonly response: CapaActionPlanAdvisoryResponse; readonly trace: ReturnType<typeof createCapaActionPlanAdvisoryGenerationTrace> }> {
    const run_id = this.dependencies.createRunId(); const prompt_package_id = this.dependencies.createPromptPackageId(); const output_id = this.dependencies.createOutputId(); const assembled_at = this.dependencies.now(); const prompt = buildCapaActionPlanAdvisoryPrompt({ model_safe_context: input.context.model_safe_context });
    const trace = createCapaActionPlanAdvisoryGenerationTrace({ rendered_prompt: prompt, model_profile_version: CAPA_ACTION_PLAN_ADVISORY_MODEL_PROFILE.profile_version, output_schema_name: CAPA_ACTION_PLAN_ADVISORY_MODEL_PROFILE.output_schema_name, output_schema: CAPA_ACTION_PLAN_ADVISORY_JSON_SCHEMA, maximum_output_characters: CAPA_ACTION_PLAN_ADVISORY_MODEL_PROFILE.maximum_output_characters, package: { scope: { organization_id: input.context.authoritative.organization_id, capa_case_id: input.context.authoritative.capa_case_id, case_version_id: input.context.authoritative.case_version_id, record_version: input.context.authoritative.record_version, workflow_state: "S60" }, agent: { agent_id: "AG-ACTION", agent_version: "ag-action-1.0.0" }, trace: { run_id, prompt_package_id, request_id: input.request_id, correlation_id: input.correlation_id, assembled_at }, context_provenance: { model_safe_context: input.context.model_safe_context }, governance: { advisory_only: true, workflow_mutated: false, controlled_record_mutated: false, human_acceptance_required: true } } });
    const result = await this.dependencies.model_client.generateStructured({ prompt, model_profile_version: CAPA_ACTION_PLAN_ADVISORY_MODEL_PROFILE.profile_version, output_schema_name: CAPA_ACTION_PLAN_ADVISORY_MODEL_PROFILE.output_schema_name, output_schema: CAPA_ACTION_PLAN_ADVISORY_JSON_SCHEMA, maximum_output_characters: CAPA_ACTION_PLAN_ADVISORY_MODEL_PROFILE.maximum_output_characters, store: false });
    const raw = validateCapaActionPlanAdvisoryModelOutput(result.output_text);
    return { response: Object.freeze({ run_id, output_id, output_schema_version: CAPA_ACTION_PLAN_ADVISORY_OUTPUT_SCHEMA_VERSION as never, status: "completed_draft" as const, proposal: raw.proposal, warnings: raw.warnings, uncertainty_and_limitations: raw.uncertainty_and_limitations, citations: [] as readonly unknown[], advisory_only: true as const, workflow_mutated: false as const, controlled_record_mutated: false as const, approval_claimed: false as const, workflow_transition: null, human_acceptance_required: true as const }), trace };
  }
}
