import type OpenAI from "openai";
import { CAPA_ACTION_PLAN_REVIEW_ADVISORY_MODEL_PROFILE, type CapaActionPlanReviewAdvisoryStructuredModelClient } from "./capa-action-plan-review-advisory-model-generator";
export class OpenAICapaActionPlanReviewAdvisoryStructuredModelClientError extends Error { constructor() { super("The governed CAPA action-plan review advisory model operation failed."); this.name = "OpenAICapaActionPlanReviewAdvisoryStructuredModelClientError"; } }
export class OpenAICapaActionPlanReviewAdvisoryStructuredModelClient implements CapaActionPlanReviewAdvisoryStructuredModelClient {
  private readonly model: string;
  constructor(private readonly client: Pick<OpenAI, "responses">, options: { readonly model: string }) { if (options.model.trim().length === 0) throw new OpenAICapaActionPlanReviewAdvisoryStructuredModelClientError(); this.model = options.model.trim(); }
  async generateStructured(input: Parameters<CapaActionPlanReviewAdvisoryStructuredModelClient["generateStructured"]>[0]): Promise<{ readonly output_text: string }> { if (input.model_profile_version !== CAPA_ACTION_PLAN_REVIEW_ADVISORY_MODEL_PROFILE.profile_version || input.output_schema_name !== CAPA_ACTION_PLAN_REVIEW_ADVISORY_MODEL_PROFILE.output_schema_name || input.maximum_output_characters !== CAPA_ACTION_PLAN_REVIEW_ADVISORY_MODEL_PROFILE.maximum_output_characters || input.store !== false) throw new OpenAICapaActionPlanReviewAdvisoryStructuredModelClientError(); try { const response = await this.client.responses.create({ model: this.model, input: input.prompt, store: false, text: { format: { type: "json_schema", name: input.output_schema_name, schema: input.output_schema, strict: true } } }); if (typeof response.output_text !== "string" || response.output_text.length === 0 || response.output_text.length > CAPA_ACTION_PLAN_REVIEW_ADVISORY_MODEL_PROFILE.maximum_output_characters) throw new Error(); return { output_text: response.output_text }; } catch { throw new OpenAICapaActionPlanReviewAdvisoryStructuredModelClientError(); } }
}
export function createOpenAICapaActionPlanReviewAdvisoryStructuredModelClient(client: Pick<OpenAI, "responses">, options: { readonly model: string }): CapaActionPlanReviewAdvisoryStructuredModelClient { return new OpenAICapaActionPlanReviewAdvisoryStructuredModelClient(client, options); }
