import { describe, expect, it, vi } from "vitest";
import { InMemoryCapaDatabase } from "../../lib/database/in-memory/in-memory-capa-database";
import { constructCapaInvestigationActiveAdoption } from "../../lib/capa/ai/capa-investigation-active-adoption-validator";
import { createCapaInvestigationActiveAdvisoryReferenceManifest } from "../../lib/capa/ai/capa-investigation-active-advisory-reference-manifest";
import { submitCapaRootCausePackage, type SubmitCapaRootCausePackageDependencies } from "../../lib/capa/application/submit-capa-root-cause-package";

const ORG = "10000000-0000-4000-8000-000000000001"; const USER = "20000000-0000-4000-8000-000000000001"; const CASE = "30000000-0000-4000-8000-000000000001"; const V4 = "40000000-0000-4000-8000-000000000004"; const V5 = "40000000-0000-4000-8000-000000000005"; const PLAN = "50000000-0000-4000-8000-000000000001"; const LEDGER = "50000000-0000-4000-8000-000000000002"; const ROOT = "50000000-0000-4000-8000-000000000003"; const AUDIT = "60000000-0000-4000-8000-000000000001"; const OUTPUT = "70000000-0000-4000-8000-000000000001"; const RUN = "70000000-0000-4000-8000-000000000002"; const REQUEST = "80000000-0000-4000-8000-000000000001"; const CORRELATION = "80000000-0000-4000-8000-000000000002"; const GAP_ADOPTION = "90000000-0000-4000-8000-000000000001"; const HYP_ADOPTION = "90000000-0000-4000-8000-000000000002"; const NOW = "2026-09-05T12:00:00.000Z";
const human = { source_type: "human" as const, source_reference: null, adopted_by_user_id: null, adopted_at: null };
const ai = (id: string, user = USER, at = NOW) => ({ source_type: "ai_proposal" as const, source_reference: id, adopted_by_user_id: user, adopted_at: at });
const trace = (key: string) => ({ request_id: REQUEST, correlation_id: CORRELATION, idempotency_key: key } as never);
const authentication = () => ({ principal: { principal_type: "human", user_id: USER }, session_id: "session", authentication_method: "SUPABASE_SESSION", assurance_level: "SINGLE_FACTOR", authenticated_at: NOW, expires_at: "2026-09-06T12:00:00.000Z" } as never);
const tenant = () => ({ organization_id: ORG, access_grant_id: "grant", access_path: "ORGANIZATION", authorization_policy_version: "policy-1", resolved_at: NOW, role_assignments: [] } as never);
const plan = (status = "completed") => ({ items: [{ item_id: "INV-1", investigation_question: "Why?", evidence_target: "Record", investigation_method: "Review", owner_user_id: USER, due_date: "2026-09-30", sme_user_ids: [], dependency_item_ids: [], scope_relationship: "Scope", status, disposition: null, disposition_rationale: null, draft_provenance: human }] });
const baseEvidence = () => ({ item_id: "E-1", information_class: "verified_evidence", statement: "Controlled inspection verified seal wear.", evidence_status: "verified", assumption_status: null, gap_status: null, conflict_status: null, provenance: human, owner_user_id: null, information_date: null, source_version: null, context: null, linked_capa_objects: [], supporting_item_ids: [], contradictory_item_ids: [], conflict_item_ids: [], material_to_conclusion: false, critical_to_conclusion: false, recommended_next_step: null, target_date: null, human_disposition: { user_id: USER, disposition_at: NOW, rationale: "Human reviewed the inspection." } });
const gap = (provenance = ai(GAP_ADOPTION), statement = "Configuration record is missing.") => ({ item_id: "LED-AI", information_class: "missing_information", statement, evidence_status: null, assumption_status: null, gap_status: "open", conflict_status: null, provenance, owner_user_id: null, information_date: null, source_version: null, context: "The missing record can affect causal analysis.", linked_capa_objects: [], supporting_item_ids: [], contradictory_item_ids: [], conflict_item_ids: [], material_to_conclusion: false, critical_to_conclusion: false, recommended_next_step: "Review configuration archive.", target_date: null, human_disposition: null });
const confirmed = () => ({ hypothesis_id: "H-human", statement: "Seal wear caused the event.", status: "confirmed", causal_role: "proposed_root_cause", rationale: "Supported by verified inspection.", responsible_user_id: USER, supporting_evidence_item_ids: ["E-1"], contradictory_evidence_item_ids: [], linked_assumption_item_ids: [], linked_gap_item_ids: [], linked_conflict_item_ids: [], material_to_package: true, provenance: human });
const aiHypothesis = (provenance = ai(HYP_ADOPTION), statement = "Configuration variation may have contributed.") => ({ hypothesis_id: "H-AI", statement, status: "proposed", causal_role: "contributing_factor", rationale: "The missing configuration record warrants evaluation.", responsible_user_id: null, supporting_evidence_item_ids: ["E-1"], contradictory_evidence_item_ids: [], linked_assumption_item_ids: [], linked_gap_item_ids: [], linked_conflict_item_ids: [], material_to_package: false, provenance });
const body = (overrides: { ledger?: unknown; root?: unknown } = {}) => ({ evidence_assumption_ledger: overrides.ledger ?? { items: [baseEvidence(), gap()] }, root_cause_package: overrides.root ?? { hypotheses: [confirmed(), aiHypothesis()], root_cause_not_confirmed: null } });

async function harness() {
  let tx = 0;
  const db = new InMemoryCapaDatabase({ generate_transaction_id: () => `cs9-${++tx}` as never, now: () => new Date(NOW) });
  await db.runInTransaction(trace("seed"), async (transaction) => {
    await db.insertCase(transaction, { organization_id: ORG, capa_case_id: CASE, case_number: "CAPA-CS9", current_version_id: V4, status: "S40", record_version: 4, owner_user_id: USER, confidentiality: "CUSTOMER_CONFIDENTIAL", effective_at: NOW, created_at: NOW, updated_at: NOW, created_by: { actor_type: "human", actor_id: USER }, updated_by: { actor_type: "human", actor_id: USER } } as never);
    await db.insertSectionVersion(transaction, { organization_id: ORG, capa_case_id: CASE, section_version_id: PLAN, section_type: "CAPA.INVESTIGATION_PLAN", version_number: 1, schema_version: "capa-investigation-plan-1.0.0", content: plan(), change_reason: "G-03", effective_at: NOW, created_at: NOW, created_by: { actor_type: "human", actor_id: USER } } as never);
    await db.insertCaseVersion(transaction, { organization_id: ORG, capa_case_id: CASE, case_version_id: V4, version_number: 4, status: "S40", section_version_ids: [PLAN], change_reason: "G-03", effective_at: NOW, created_at: NOW, created_by: { actor_type: "human", actor_id: USER } } as never);
  });
  const proposal = { evidence_gaps: [{ proposal_key: "P1", gap: "Configuration record is missing.", why_it_matters: "The missing record can affect causal analysis.", related_reference_keys: [], recommended_next_step: "Review configuration archive.", human_review_question: "Should the configuration archive be reviewed?" }], conflicting_information: [], assumptions: [], causal_hypotheses: [{ proposal_key: "P2", hypothesis: "Configuration variation may have contributed.", suggested_role: "possible_contributing_factor", rationale: "The missing configuration record warrants evaluation.", supporting_reference_keys: [], contradictory_reference_keys: [], human_review_question: "Should this be evaluated as a contributing factor?" }], alternative_hypotheses: [], investigation_recommendations: [] };
  const modelSafe = { trust: "model_safe_context", workflow_state: "S40", references: [] };
  await db.runInTransaction(trace("output"), (transaction) => db.save(transaction, { context: { trust: "authoritative_server_context", organization_id: ORG, capa_case_id: CASE, case_version_id: V4, record_version: 4, workflow_state: "S40", actor: USER, active_roles: [], investigation_plan: plan() }, response: { run_id: RUN, output_id: OUTPUT, output_schema_version: "capa_investigation_analysis_draft-1.0.0", status: "completed_draft", proposal, uncertainty_and_limitations: [], citations: [], warnings: [], advisory_only: true, workflow_mutated: false, human_acceptance_required: true }, generation_trace: { trace_schema_version: "capa-ai-generation-trace-1.0.0", package: { package_schema_version: "capa-investigation-active-prompt-package-1.0.0", scope: { organization_id: ORG, capa_case_id: CASE, case_version_id: V4, record_version: 4, workflow_state: "S40" }, agent: { agent_id: "AG-RCA", agent_version: "ag-rca-1.0.0" }, trace: { run_id: RUN, prompt_package_id: "70000000-0000-4000-8000-000000000003", request_id: REQUEST, correlation_id: CORRELATION, assembled_at: NOW }, context_provenance: { model_safe_context: modelSafe }, generation_contract: { operation: "facilitate_root_cause", requested_output: "investigation_analysis_draft", output_schema_version: "capa_investigation_analysis_draft-1.0.0" } }, store: false, evidence_manifest: { evidence_manifest_schema_version: "capa-investigation-active-evidence-manifest-1.0.0", retrieval_performed: false, item_count: 0, items: [] }, policy_manifest: { policy_manifest_schema_version: "capa-investigation-active-policy-manifest-1.0.0", agent: { agent_id: "AG-RCA", agent_version: "ag-rca-1.0.0" }, workflow_state: "S40", operation: "facilitate_root_cause", requested_output: "investigation_analysis_draft", output_schema_version: "capa_investigation_analysis_draft-1.0.0", authority: { advisory_only: true, workflow_mutated: false, human_acceptance_required: true } }, fingerprints: { algorithm: "sha256-canonical-json-v1" } }, reference_manifest: [], request_id: REQUEST, correlation_id: CORRELATION } as never));
  const manifest = createCapaInvestigationActiveAdvisoryReferenceManifest({ reference_manifest: [], model_safe_context: modelSafe as never });
  async function persist(id: string, proposalKey: "P1" | "P2") {
    const category = proposalKey === "P1" ? "evidence_gap" : "causal_hypothesis" as const;
    const content = proposalKey === "P1" ? { gap: "Configuration record is missing.", why_it_matters: "The missing record can affect causal analysis.", recommended_next_step: "Review configuration archive." } : { hypothesis: "Configuration variation may have contributed.", rationale: "The missing configuration record warrants evaluation." };
    const adoption = constructCapaInvestigationActiveAdoption({ adoption_id: id as never, organization_id: ORG as never, capa_case_id: CASE as never, case_version_id: V4 as never, record_version: 4, output_id: OUTPUT, proposal_key: proposalKey, proposal_category: category, adopted_item: { proposal_key: proposalKey, adopted_content: content }, resolved_reference_bindings: [], reference_manifest_schema_version: manifest.document.manifest_schema_version, reference_manifest_fingerprint_algorithm: manifest.fingerprint_algorithm, reference_manifest_sha256: manifest.reference_manifest_sha256, adopted_at: NOW as never, adopted_by: { actor_type: "human", actor_id: USER }, request_id: REQUEST as never, correlation_id: CORRELATION as never, idempotency_key: `adopt-${proposalKey}` as never, workflow_mutated: false, controlled_record_mutated: false, gate_approved: false });
    const auditEventId = (proposalKey === "P1" ? "90000000-0000-4000-8000-000000000010" : "90000000-0000-4000-8000-000000000011") as never;
    await db.runInTransaction(trace(`adopt-${proposalKey}`), async (transaction) => {
      await db.appendAdoption(transaction, { adoption, request_fingerprint: "a".repeat(64) as never, record_fingerprint: "b".repeat(64) as never, audit_event_id: auditEventId });
      await db.appendEvent(transaction, { organization_id: ORG, event_id: auditEventId, event_type: "EVT-AI-PROPOSAL-ADOPTED" as never, schema_version: "audit-1", aggregate_type: "CAPA_CASE" as never, aggregate_id: CASE, aggregate_version: 4, actor: adoption.adopted_by, occurred_at: NOW, request_id: REQUEST, correlation_id: CORRELATION, action: "ADOPT_CAPA_INVESTIGATION_ACTIVE_AI_PROPOSALS" as never, target: { object_type: "CAPA_INVESTIGATION_ACTIVE_ADOPTION" as never, object_id: adoption.adoption_id }, outcome: "succeeded", configuration_versions: {}, metadata: {} } as never);
    });
  }
  await persist(GAP_ADOPTION, "P1"); await persist(HYP_ADOPTION, "P2");
  const dependencies: SubmitCapaRootCausePackageDependencies = { transaction_manager: db, capa_repository: db, audit_repository: db, adoption_repository: db, workflow_idempotency_repository: db, authorization_policy: { evaluate: vi.fn().mockResolvedValue({ decision: "allow", reason_code: "AUTHORIZED", policy_version: "policy-1", evaluated_at: NOW, relied_on_role_assignment_ids: [] }) }, id_generator: { generateCaseVersionId: () => V5, generateSectionVersionId: (() => { let i = 0; return () => [LEDGER, ROOT][i++ % 2]!; })(), generateAuditEventId: () => AUDIT } as never, clock: { now: () => new Date(NOW) }, configuration: { workflow_version: "workflow-1", audit_schema_version: "audit-1", authorization_purpose: "CAPA_WORKFLOW_TRANSITION" as never } };
  const submit = (applicationBody = body(), key = "submit") => submitCapaRootCausePackage(dependencies, { authentication: authentication(), tenant: tenant(), capa_case_id: CASE, expected_record_version: 4, expected_current_version_id: V4, request_trace: trace(key), body: applicationBody } as never);
  return { db, dependencies, submit };
}

describe("S40 durable AG-RCA provenance submission gate lifecycle", () => {
  it("accepts valid durable ledger and causal provenance, persists S50 sections/audit, and replays exactly", async () => {
    const test = await harness(); const submitted = body(); const first = await test.submit(submitted, "submit-valid");
    expect(first).toMatchObject({ status: "submitted", capa_case: { status: "S50", record_version: 5, current_version_id: V5 }, case_version: { status: "S50", section_version_ids: expect.arrayContaining([PLAN, LEDGER, ROOT]) } });
    if (first.status !== "submitted") throw new Error("Expected successful S50 submission.");
    expect(first.evidence_assumption_ledger_section_version.content).toEqual(submitted.evidence_assumption_ledger);
    expect(first.root_cause_package_section_version.content).toEqual(submitted.root_cause_package);
    expect(first.case_version.section_version_ids).toContain(PLAN);
    expect(await test.db.findEventById(ORG as never, AUDIT as never)).toMatchObject({ event_type: "EVT-STATE-TRANSITION", action: "SUBMIT_CAPA_ROOT_CAUSE_PACKAGE", actor: { actor_type: "human", actor_id: USER } });
    const persisted = { caseVersion: await test.db.findCaseVersionById(ORG as never, CASE as never, V5 as never), ledger: await test.db.findSectionVersionById(ORG as never, CASE as never, LEDGER as never), rootCause: await test.db.findSectionVersionById(ORG as never, CASE as never, ROOT as never), audit: await test.db.findEventById(ORG as never, AUDIT as never) };
    const replay = await test.submit(submitted, "submit-valid"); expect(replay).toMatchObject({ status: "already_submitted", capa_case: { current_version_id: V5 } });
    await expect(test.db.findCaseVersionById(ORG as never, CASE as never, V5 as never)).resolves.toEqual(persisted.caseVersion);
    await expect(test.db.findSectionVersionById(ORG as never, CASE as never, LEDGER as never)).resolves.toEqual(persisted.ledger);
    await expect(test.db.findSectionVersionById(ORG as never, CASE as never, ROOT as never)).resolves.toEqual(persisted.rootCause);
    await expect(test.db.findEventById(ORG as never, AUDIT as never)).resolves.toEqual(persisted.audit);
  });
  it("does not claim workflow idempotency when provenance blocks", async () => {
    const test = await harness(); const invalid: any = body(); invalid.evidence_assumption_ledger.items[1].provenance.source_reference = "90000000-0000-4000-8000-000000000099";
    await expect(test.submit(invalid, "provenance-before-idempotency")).resolves.toEqual({ status: "submission_blocked", reason_codes: ["AI_PROPOSAL_NOT_HUMAN_ADOPTED"], canonical_blocker_codes: [] });
    expect(await test.db.findCaseById(ORG as never, CASE as never)).toMatchObject({ status: "S40", record_version: 4 });
    await expect(test.submit(body(), "provenance-before-idempotency")).resolves.toMatchObject({ status: "submitted" });
  });
  it("allows human-controlled post-adoption fields but blocks missing adoption, identity drift, core drift, and reuse", async () => {
    const valid = await harness(); const edited: any = body(); (edited.evidence_assumption_ledger.items[1] as any).target_date = "2026-09-20"; (edited.root_cause_package.hypotheses[1] as any).material_to_package = true;
    await expect(valid.submit(edited, "submit-edited")).resolves.toMatchObject({ status: "submitted" });
    for (const mutation of [
      (value: any) => { value.evidence_assumption_ledger.items[1].provenance.source_reference = "90000000-0000-4000-8000-000000000099"; },
      (value: any) => { value.evidence_assumption_ledger.items[1].provenance.adopted_by_user_id = "20000000-0000-4000-8000-000000000099"; },
      (value: any) => { value.evidence_assumption_ledger.items[1].provenance.adopted_at = "2026-09-05T12:00:01.000Z"; },
      (value: any) => { value.evidence_assumption_ledger.items[1].statement = "Drifted core content"; },
      (value: any) => { value.root_cause_package.hypotheses[1].rationale = "Drifted rationale"; },
      (value: any) => { value.evidence_assumption_ledger.items.push({ ...value.evidence_assumption_ledger.items[1], item_id: "LED-DUP" }); },
    ]) { const test = await harness(); const candidate: any = body(); mutation(candidate); await expect(test.submit(candidate, `blocked-${Math.random()}`)).resolves.toEqual({ status: "submission_blocked", reason_codes: ["AI_PROPOSAL_NOT_HUMAN_ADOPTED"], canonical_blocker_codes: [] }); expect(await test.db.findCaseById(ORG as never, CASE as never)).toMatchObject({ status: "S40", record_version: 4 }); }
    for (const mismatch of [{ case_version_id: V5 }, { record_version: 5 }]) {
      const test = await harness(); const real = test.db.findAdoptionById.bind(test.db);
      (test.dependencies as any).adoption_repository = { findAdoptionById: async (organizationId: any, adoptionId: any) => { const persisted: any = await real(organizationId, adoptionId); return persisted === null ? null : { ...persisted, adoption: { ...persisted.adoption, ...mismatch } }; } };
      await expect(test.submit(body(), `identity-${Object.keys(mismatch)[0]}`)).resolves.toEqual({ status: "submission_blocked", reason_codes: ["AI_PROPOSAL_NOT_HUMAN_ADOPTED"], canonical_blocker_codes: [] });
    }
  });
  it("rejects AI root-cause-not-confirmed structurally before provenance, and readiness precedes adoption lookup", async () => {
    const test = await harness(); const invalid: any = body({ root: { hypotheses: [], root_cause_not_confirmed: { rationale: "AI conclusion", next_steps: ["Continue"], concluded_by_user_id: USER, concluded_at: NOW, provenance: ai(GAP_ADOPTION) } } });
    await expect(test.submit(invalid, "invalid-not-confirmed")).resolves.toMatchObject({ status: "validation_failed", reason_code: "INVALID_ROOT_CAUSE_PACKAGE" });
    const lookup = vi.spyOn(test.db, "findAdoptionById"); const structurallyBlocked: any = body({ ledger: { items: [baseEvidence(), { ...gap(ai("90000000-0000-4000-8000-000000000099")), critical_to_conclusion: true }] } });
    await expect(test.submit(structurallyBlocked, "structural-first")).resolves.toMatchObject({ status: "submission_blocked", reason_codes: expect.arrayContaining(["UNRESOLVED_CRITICAL_EVIDENCE_GAP"]) }); expect(lookup).not.toHaveBeenCalled();
  });
  it("does not advance a stale S40 request", async () => {
    const test = await harness(); const result = await submitCapaRootCausePackage(test.dependencies, { authentication: authentication(), tenant: tenant(), capa_case_id: CASE, expected_record_version: 3, expected_current_version_id: V4, request_trace: trace("stale"), body: body() } as never);
    expect(result).toMatchObject({ status: "submission_blocked", reason_codes: ["AI_PROPOSAL_NOT_HUMAN_ADOPTED"] }); expect(await test.db.findCaseById(ORG as never, CASE as never)).toMatchObject({ status: "S40", record_version: 4 });
  });
});
