import { BRAND } from "@/lib/branding";

export default function TermsPage() {
  const address = BRAND.contact.address;

  return (
    <main className="min-h-screen bg-[#020817] px-6 py-16 text-white">
      <div className="mx-auto max-w-3xl">
        <h1 className="text-4xl font-semibold">Terms of Service</h1>

        <p className="mt-4 text-sm text-white/60">
          Effective date: {new Date().toLocaleDateString()}
        </p>

        <section className="mt-8 space-y-6 text-white/75 text-sm leading-7">
          <p>
            By using {BRAND.name}, you agree to these Terms of Service. If you
            do not agree, you should not use the service.
          </p>

          <div>
            <h2 className="text-lg font-semibold text-white">
              Use of Service
            </h2>
            <p className="mt-2">
              You agree to use {BRAND.name} only for lawful purposes and in
              compliance with all applicable laws.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-white">
              AI-Generated Content
            </h2>
            <p className="mt-2">
              Responses generated by AI may not always be accurate. You are
              responsible for verifying important information.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-white">
              Account Responsibility
            </h2>
            <p className="mt-2">
              You are responsible for maintaining the security of your account
              and any activity under it.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-white">
              Limitation of Liability
            </h2>
            <p className="mt-2">
              {BRAND.name} is provided “as is” without warranties. We are not
              liable for any damages resulting from use of the service.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-white">
              Termination
            </h2>
            <p className="mt-2">
              We may suspend or terminate access to the service at any time for
              violations of these terms.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-white">
              Governing Law
            </h2>
            <p className="mt-2">
              These terms are governed by the laws of {BRAND.legal.jurisdiction}.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-white">Contact</h2>
            <p className="mt-2">
              {BRAND.legal.company}
              <br />
              {address.line1}
              <br />
              {address.line2}
              <br />
              {address.city}, {address.state} {address.postalCode}
              <br />
              {address.country}
              <br />
              {BRAND.contact.email}
            </p>
          </div>
        </section>
      </div>
    </main>
  );
}