import type { IsoDateTime } from "../domain/capa-types";
import type { CapaRepository } from "../../database/repositories/capa-repository";
import type { TransactionManager } from "../../database/transactions";
import type { CapaRequestContext } from "../../security/supabase-capa-context";
import type { CapaAuthorizationPolicy } from "../authorization/capa-policy";
import type { CapaAgentActivationService } from "../ai/capa-agent-activation-service";
import { createActivationBackedCapaActionPlanReviewAdvisoryAgentGate } from "../ai/capa-action-plan-review-advisory-agent-gate";
import { CapaActionPlanReviewAdvisoryModelGenerator, type CapaActionPlanReviewAdvisoryStructuredModelClient } from "../ai/capa-action-plan-review-advisory-model-generator";
import { CapaActionPlanReviewAdvisoryService } from "../ai/capa-action-plan-review-advisory-service";
import { RepositoryCapaActionPlanReviewAdvisoryContextResolver } from "../ai/repository-capa-action-plan-review-advisory-context-resolver";
import { PolicyBackedCapaActionPlanReviewAdvisoryAuthorizer } from "../authorization/capa-action-plan-review-advisory-authorizer";
import type { CapaActionPlanReviewAdvisoryOutputRepository } from "../../database/repositories/capa-action-plan-review-advisory-output-repository";
import type { CapaAiOutputId, CapaAiRunId, CapaPromptPackageId } from "../ai/capa-prompt-contract";
function trustedIsoNow(now: () => Date): IsoDateTime { const value = now(); if (!Number.isFinite(value.getTime())) throw new Error("CONTROLLED_CLOCK_INVALID"); return value.toISOString() as IsoDateTime; }
export interface CapaActionPlanReviewAdvisoryRuntimeFactoryDependencies { readonly request_context: CapaRequestContext; readonly capa_repository: CapaRepository; readonly authorization_policy: CapaAuthorizationPolicy; readonly agent_activation_service: CapaAgentActivationService; readonly structured_model_client: CapaActionPlanReviewAdvisoryStructuredModelClient; readonly output_repository: CapaActionPlanReviewAdvisoryOutputRepository; readonly transaction_manager: TransactionManager; readonly now: () => Date; readonly generate_uuid: () => string; }
export function createRequestScopedCapaActionPlanReviewAdvisoryService(dependencies: CapaActionPlanReviewAdvisoryRuntimeFactoryDependencies): CapaActionPlanReviewAdvisoryService { const resolver = new RepositoryCapaActionPlanReviewAdvisoryContextResolver({ repository: dependencies.capa_repository, authentication: dependencies.request_context.authentication, tenant: dependencies.request_context.tenant, now: dependencies.now }); const authorizer = new PolicyBackedCapaActionPlanReviewAdvisoryAuthorizer({ authentication: dependencies.request_context.authentication, tenant: dependencies.request_context.tenant, policy: dependencies.authorization_policy, now: dependencies.now }); const generator = new CapaActionPlanReviewAdvisoryModelGenerator({ model_client: dependencies.structured_model_client, createRunId: () => dependencies.generate_uuid() as CapaAiRunId, createPromptPackageId: () => dependencies.generate_uuid() as CapaPromptPackageId, createOutputId: () => dependencies.generate_uuid() as CapaAiOutputId, now: () => trustedIsoNow(dependencies.now) }); return new CapaActionPlanReviewAdvisoryService({ context_resolver: resolver, authorizer, agent_gate: createActivationBackedCapaActionPlanReviewAdvisoryAgentGate(dependencies.agent_activation_service), generator, output_repository: dependencies.output_repository, transaction_manager: dependencies.transaction_manager }); }
