import type { CapaActionPlanReviewAdvisoryResponse } from "../../capa/ai/capa-action-plan-review-advisory-contract";
import type { CapaActionPlanReviewAdvisoryGenerationTraceCapture } from "../../capa/ai/capa-action-plan-review-advisory-model-generator";
import type { AuthoritativeS70ActionPlanReviewContext, CapaActionPlanReviewAdvisoryReferenceManifestEntry } from "../../capa/ai/capa-action-plan-review-advisory-context";
import type { CorrelationId, RequestId } from "../../capa/domain/capa-types";
import type { TransactionContext } from "../transactions";
export type CapaActionPlanReviewAdvisoryOutputSaveResult = "saved" | "case_changed";
export interface CapaActionPlanReviewAdvisoryReferenceManifest { readonly document: Readonly<{ readonly manifest_schema_version: "capa-action-plan-review-advisory-reference-manifest-1.0.0"; readonly source_case_version_id: string; readonly action_plan_section_version_id: string; readonly entries: readonly CapaActionPlanReviewAdvisoryReferenceManifestEntry[] }>; readonly fingerprint_algorithm: "sha256-canonical-json-v1"; readonly reference_manifest_sha256: string; }
export interface CapaActionPlanReviewAdvisoryOutputRecord { readonly organization_id: string; readonly capa_case_id: string; readonly case_version_id: string; readonly record_version: number; readonly request_trace: Readonly<{ request_id: RequestId; correlation_id: CorrelationId }>; readonly response: CapaActionPlanReviewAdvisoryResponse; readonly generation_trace: CapaActionPlanReviewAdvisoryGenerationTraceCapture; readonly reference_manifest: CapaActionPlanReviewAdvisoryReferenceManifest; }
export interface CapaActionPlanReviewAdvisoryOutputRepository { save(transaction: TransactionContext, input: { readonly context: AuthoritativeS70ActionPlanReviewContext; readonly response: CapaActionPlanReviewAdvisoryResponse; readonly generation_trace: CapaActionPlanReviewAdvisoryGenerationTraceCapture; readonly reference_manifest: readonly CapaActionPlanReviewAdvisoryReferenceManifestEntry[]; readonly request_id: RequestId; readonly correlation_id: CorrelationId }): Promise<CapaActionPlanReviewAdvisoryOutputSaveResult>; findById(organizationId: string, outputId: string): Promise<CapaActionPlanReviewAdvisoryOutputRecord | null>; }
