import { describe, expect, it } from "vitest";
import { InMemoryCapaDatabase } from "../../lib/database/in-memory/in-memory-capa-database";
import { CAPA_INVESTIGATION_ACTIVE_WORKSPACE_DRAFT_SCHEMA_VERSION } from "../../lib/capa/application/capa-investigation-active-workspace-draft-contract";
import { validateCapaDevelopmentStateSnapshot } from "../../lib/database/development/capa-development-state-snapshot";
const ORG = "10000000-0000-4000-8000-000000000001" as never; const CASE = "20000000-0000-4000-8000-000000000001" as never; const AT = "2026-09-05T12:00:00.000Z" as never;
function db(snapshot?: any) { let n = 0; return new InMemoryCapaDatabase({ generate_transaction_id: () => `t-${++n}` as never, now: () => new Date(AT), initial_snapshot: snapshot }); }
const draft = { schema_version: CAPA_INVESTIGATION_ACTIVE_WORKSPACE_DRAFT_SCHEMA_VERSION, trust: "untrusted_human_draft", workflow_state: "S40", organization_id: ORG, capa_case_id: CASE, case_version_id: "30000000-0000-4000-8000-000000000001" as never, record_version: 4, draft_revision: 1, evidence_assumption_ledger: { items: [] }, root_cause_package: { hypotheses: [], root_cause_not_confirmed: null }, updated_by_user_id: "40000000-0000-4000-8000-000000000001" as never, updated_at: AT } as const;
const nonEmptyDraft: any = { ...draft, record_version: 4, draft_revision: 2, evidence_assumption_ledger: { items: [{ item_id: "G-1", information_class: "missing_information", statement: "The controlled record is unavailable.", evidence_status: null, assumption_status: null, gap_status: "open", conflict_status: null, provenance: { source_type: "ai_proposal", source_reference: "50000000-0000-4000-8000-000000000001", adopted_by_user_id: "40000000-0000-4000-8000-000000000001", adopted_at: AT }, owner_user_id: null, information_date: null, source_version: null, context: null, linked_capa_objects: [], supporting_item_ids: [], contradictory_item_ids: [], conflict_item_ids: [], material_to_conclusion: false, critical_to_conclusion: false, recommended_next_step: "Review the archive.", target_date: null, human_disposition: null }] }, root_cause_package: { hypotheses: [{ hypothesis_id: "H-1", statement: "A process variation may have contributed.", status: "proposed", causal_role: "proposed_root_cause", rationale: "The gap warrants review.", responsible_user_id: null, supporting_evidence_item_ids: [], contradictory_evidence_item_ids: [], linked_assumption_item_ids: [], linked_gap_item_ids: [], linked_conflict_item_ids: [], material_to_package: false, provenance: { source_type: "ai_proposal", source_reference: "50000000-0000-4000-8000-000000000001", adopted_by_user_id: "40000000-0000-4000-8000-000000000001", adopted_at: AT } }], root_cause_not_confirmed: null } };
describe("S40 workspace development snapshot", () => {
  it("exports, restores, and backward-compatibly defaults the workspace collection", async () => { const source = db(); await source.runInTransaction({ request_id: "r" as never, correlation_id: "c" as never }, (tx) => source.saveDraft(tx, { draft, expected_draft_revision: null })); const snapshot = source.exportSnapshot(); expect(snapshot.investigation_active_workspace_drafts).toHaveLength(1); expect((await db(snapshot).findDraft(ORG, CASE))?.draft_revision).toBe(1); const { investigation_active_workspace_drafts: _legacy, ...legacy } = snapshot; expect(validateCapaDevelopmentStateSnapshot(legacy)).toMatchObject({ investigation_active_workspace_drafts: [] }); });
  it("round-trips non-empty AI-provenance workspace payloads exactly", async () => { const source = db(); await source.runInTransaction({ request_id: "r" as never, correlation_id: "c" as never }, (tx) => source.saveDraft(tx, { draft, expected_draft_revision: null })); await source.runInTransaction({ request_id: "r2" as never, correlation_id: "c2" as never }, (tx) => source.saveDraft(tx, { draft: nonEmptyDraft, expected_draft_revision: 1 })); const restored = await db(validateCapaDevelopmentStateSnapshot(source.exportSnapshot())).findDraft(ORG, CASE); expect(restored).toMatchObject({ draft_revision: 2, record_version: 4, case_version_id: draft.case_version_id, evidence_assumption_ledger: { items: [expect.objectContaining({ item_id: "G-1", provenance: nonEmptyDraft.evidence_assumption_ledger.items[0].provenance })] }, root_cause_package: { hypotheses: [expect.objectContaining({ hypothesis_id: "H-1", provenance: nonEmptyDraft.root_cause_package.hypotheses[0].provenance })] } }); });
  it("fails closed for malformed, duplicate, and unexpected snapshot entries", () => { const snapshot = db().exportSnapshot(); expect(() => validateCapaDevelopmentStateSnapshot({ ...snapshot, unexpected: true })).toThrow(); expect(() => validateCapaDevelopmentStateSnapshot({ ...snapshot, investigation_active_workspace_drafts: [["x", {}]] })).toThrow(); expect(() => validateCapaDevelopmentStateSnapshot({ ...snapshot, investigation_active_workspace_drafts: [["x", draft], ["x", draft]] })).toThrow(); });
});
