import { describe, expect, it, vi } from "vitest";
import { CapaContainmentRiskAdvisoryService } from "../../lib/capa/ai/capa-containment-risk-advisory-service";
const advisory:any={proposal:{missing_risk_inputs:[],missing_impact_dimensions:[],human_review_questions:["May distribution resume?"],evidence_provenance_gaps:[]},assumptions:[],uncertainty_and_limitations:[],citations:[],advisory_only:true,workflow_mutated:false,human_acceptance_required:true};
const context:any={authoritative:{trust:"authoritative_server_context",organization_id:"o",capa_case_id:"c",case_version_id:"v",record_version:2,workflow_state:"S20",actor:"u",active_roles:[{}],intake_scope:{},persisted_containment_risk:null},untrusted_human_draft:null};
function setup(){const resolver={resolve:vi.fn().mockResolvedValue(context),assertCaseUnchanged:vi.fn().mockResolvedValue(true)};const authorizer={authorize:vi.fn().mockResolvedValue(true)};const gate={evaluate:vi.fn().mockReturnValue(true)};const generator={generate:vi.fn().mockResolvedValue(advisory)};return {service:new CapaContainmentRiskAdvisoryService({context_resolver:resolver,authorizer,agent_gate:gate,generator}),resolver,authorizer,gate,generator};}
const invocation:any={organization_id:"o",capa_case_id:"c",user_id:"u",request:{requested_output:"containment_risk_analysis",focus:null,untrusted_human_draft:null}};
describe("S20 advisory service",()=>{it("orchestrates and revalidates",async()=>{const t=setup();const r=await t.service.execute(invocation);expect(r.snapshot).toEqual({capa_case_id:"c",case_version_id:"v",record_version:2});expect(t.resolver.resolve).toHaveBeenCalledTimes(1);expect(t.resolver.resolve).toHaveBeenCalledWith({organization_id:"o",capa_case_id:"c",untrusted_human_draft:null});expect(t.authorizer.authorize).toHaveBeenCalledWith({context:context.authoritative,operation:"analyze_containment_impact_risk"});expect(t.gate.evaluate).toHaveBeenCalledWith(expect.objectContaining({context:context.authoritative,agent:expect.objectContaining({agent_id:"AG-INTAKE"})}));expect(t.generator.generate).toHaveBeenCalledWith({context,focus:null});expect(t.resolver.assertCaseUnchanged).toHaveBeenCalledWith(context.authoritative);expect(Object.isFrozen(r)).toBe(true);expect(Object.isFrozen(r.advisory)).toBe(true);});
it("keeps draft out of authorization but passes it to generator",async()=>{const t=setup();const assembly={...context,untrusted_human_draft:{trust:"untrusted_human_draft",content:{x:1}}};t.resolver.resolve.mockResolvedValue(assembly);await t.service.execute(invocation);expect(t.authorizer.authorize.mock.calls[0][0].context).toBe(context.authoritative);expect(t.gate.evaluate.mock.calls[0][0].context).toBe(context.authoritative);expect(t.generator.generate.mock.calls[0][0].context).toBe(assembly);});
for(const [name,mutate,reason] of [["null",(t:any)=>t.resolver.resolve.mockResolvedValue(null),"CASE_NOT_FOUND_OR_NOT_AUTHORIZED"],["wrong trust",(t:any)=>t.resolver.resolve.mockResolvedValue({...context,authoritative:{...context.authoritative,trust:"bad"}}),"CASE_NOT_IN_CONTAINMENT_RISK"],["bad version",(t:any)=>t.resolver.resolve.mockResolvedValue({...context,authoritative:{...context.authoritative,case_version_id:undefined}}),"CASE_NOT_IN_CONTAINMENT_RISK"],["bad roles",(t:any)=>t.resolver.resolve.mockResolvedValue({...context,authoritative:{...context.authoritative,active_roles:null}}),"CASE_NOT_IN_CONTAINMENT_RISK"]] as const)it(`rejects ${name}`,async()=>{const t=setup();mutate(t);await expect(t.service.execute(invocation)).rejects.toMatchObject({reason_code:reason});expect(t.generator.generate).not.toHaveBeenCalled();});
it("reports denial, gate, generation and integrity failures",async()=>{const a=setup();a.authorizer.authorize.mockResolvedValue(false);await expect(a.service.execute(invocation)).rejects.toMatchObject({reason_code:"ADVISORY_ACCESS_DENIED"});const g=setup();g.gate.evaluate.mockReturnValue(false);await expect(g.service.execute(invocation)).rejects.toMatchObject({reason_code:"AGENT_NOT_ELIGIBLE"});const x=setup();x.generator.generate.mockRejectedValue(new Error());await expect(x.service.execute(invocation)).rejects.toMatchObject({reason_code:"ADVISORY_GENERATION_FAILED"});const s=setup();s.resolver.assertCaseUnchanged.mockRejectedValue(new Error());await expect(s.service.execute(invocation)).rejects.toMatchObject({reason_code:"WORKFLOW_MUTATION_DETECTED"});});
});
