import { describe, expect, it, vi } from "vitest";
import { RepositoryCapaContainmentRiskAdvisoryContextResolver } from "../../lib/capa/ai/repository-capa-containment-risk-advisory-context-resolver";
const ORG="10000000-0000-4000-8000-000000000001" as any,CASE="30000000-0000-4000-8000-000000000001" as any,VERSION="40000000-0000-4000-8000-000000000001" as any,INTAKE="50000000-0000-4000-8000-000000000001" as any,RISK="60000000-0000-4000-8000-000000000001" as any,USER="20000000-0000-4000-8000-000000000001" as any;
const intake=(id=INTAKE)=>({organization_id:ORG,capa_case_id:CASE,section_version_id:id,section_type:"INTAKE",content:{initiating_event:"event",organization_reference:"ref",source:{source_type:"source"}}});
const risk=(id=RISK,content:any={actions:[],impact_scope:{products:[],processes:[],data:[],customers:[],patients:[]},risk_evaluation:null,missing_risk_information:[],escalations:[]})=>({organization_id:ORG,capa_case_id:CASE,section_version_id:id,section_type:"CAPA.CONTAINMENT_RISK",content});
const draft={actions:[],impact_scope:{products:[],processes:[],data:[],customers:[],patients:[]},risk_evaluation:null,missing_risk_information:[],escalations:[]};
function setup(o:any={}){const sections=o.sections??[intake()];const repository={findCaseById:vi.fn().mockResolvedValue({organization_id:ORG,capa_case_id:CASE,current_version_id:VERSION,status:"S20",record_version:2,...o.capaCase}),findCaseVersionById:vi.fn().mockResolvedValue({organization_id:ORG,capa_case_id:CASE,case_version_id:VERSION,status:"S20",version_number:2,section_version_ids:sections.map((s:any)=>s.section_version_id),...o.version}),findSectionVersionById:vi.fn().mockImplementation(async(_:any,__:any,id:any)=>sections.find((s:any)=>s.section_version_id===id)??null)};const tenant:any={organization_id:ORG,role_assignments:[{role_assignment_id:"r",role_id:"CAPA_OWNER",scope:"ORGANIZATION",effective_at:"2020-01-01T00:00:00Z"}]};const resolver=new RepositoryCapaContainmentRiskAdvisoryContextResolver({repository:repository as any,authentication:o.authentication??{principal:{principal_type:"human",user_id:USER}},tenant,intake_section_type:"INTAKE",now:o.now??(()=>new Date("2026-01-01T00:00:00Z"))});return{resolver,repository,tenant};}
const invoke=(x:any={})=>({organization_id:ORG,capa_case_id:CASE,...x});
describe("S20 context resolver qualification",()=>{
it("resolves and freezes authoritative context",async()=>{const r=await setup().resolver.resolve(invoke());expect(r?.authoritative).toMatchObject({trust:"authoritative_server_context",organization_id:ORG,capa_case_id:CASE,case_version_id:VERSION,record_version:2,workflow_state:"S20",actor:USER,intake_scope:{initiating_event:"event",organization_reference:"ref"},persisted_containment_risk:null});expect(Object.isFrozen(r)).toBe(true);expect(Object.isFrozen(r?.authoritative)).toBe(true);expect(Object.isFrozen(r?.authoritative.active_roles)).toBe(true);});
it("keeps valid draft separate and unpersisted",async()=>{const r=await setup().resolver.resolve(invoke({untrusted_human_draft:{trust:"untrusted_human_draft",content:draft}}));expect(r?.untrusted_human_draft?.trust).toBe("untrusted_human_draft");expect(Object.isFrozen(r?.untrusted_human_draft)).toBe(true);expect(r?.authoritative.persisted_containment_risk).toBeNull();});
it("preserves persisted risk over a different draft",async()=>{const p=risk();const r=await setup({sections:[intake(),p]}).resolver.resolve(invoke({untrusted_human_draft:{trust:"untrusted_human_draft",content:{...draft,missing_risk_information:["browser"]}}}));expect(r?.authoritative.persisted_containment_risk).toEqual(p.content);expect(r?.untrusted_human_draft?.content.missing_risk_information).toEqual(["browser"]);});
it("fails closed for malformed draft",async()=>{await expect(setup().resolver.resolve(invoke({untrusted_human_draft:{trust:"wrong",content:draft}} as any))).resolves.toBeNull();});
it("fails closed for clock, actor, tenant, role, case and repository failures",async()=>{for(const o of[{now:()=>{throw new Error();}},{now:()=>new Date("invalid")},{authentication:{principal:{principal_type:"service",service_identity_id:"s"}}}])expect(await setup(o).resolver.resolve(invoke())).toBeNull();const t=setup();t.tenant.organization_id="other";expect(await t.resolver.resolve(invoke())).toBeNull();const n=setup();n.tenant.role_assignments=[];expect(await n.resolver.resolve(invoke())).toBeNull();const c=setup();c.repository.findCaseById.mockResolvedValue(null);expect(await c.resolver.resolve(invoke())).toBeNull();const e=setup();e.repository.findCaseById.mockRejectedValue(new Error());expect(await e.resolver.resolve(invoke())).toBeNull();});
it("fails closed for state, versions and section binding",async()=>{expect(await setup({capaCase:{status:"S10"}}).resolver.resolve(invoke())).toBeNull();const missing=setup();missing.repository.findCaseVersionById.mockResolvedValue(null);expect(await missing.resolver.resolve(invoke())).toBeNull();expect(await setup({version:{version_number:3}}).resolver.resolve(invoke())).toBeNull();expect(await setup({version:{section_version_ids:[INTAKE]},sections:[intake("70000000-0000-4000-8000-000000000001")] }).resolver.resolve(invoke())).toBeNull();});
it("fails closed for missing/duplicate intake and duplicate/invalid risk",async()=>{expect(await setup({sections:[]}).resolver.resolve(invoke())).toBeNull();expect(await setup({sections:[intake(),intake("70000000-0000-4000-8000-000000000001")]}).resolver.resolve(invoke())).toBeNull();expect(await setup({sections:[intake(),risk(),risk("70000000-0000-4000-8000-000000000001")]}).resolver.resolve(invoke())).toBeNull();expect(await setup({sections:[intake(),risk(RISK,{})]}).resolver.resolve(invoke())).toBeNull();});
});
