import { describe, expect, it, vi } from "vitest";
import { fingerprintCanonicalJson } from "../../lib/capa/ai/capa-ai-generation-trace";
import { constructCapaInvestigationActiveAdoption } from "../../lib/capa/ai/capa-investigation-active-adoption-validator";
import { createCapaInvestigationActiveAdvisoryReferenceManifest } from "../../lib/capa/ai/capa-investigation-active-advisory-reference-manifest";
import { SupabaseCapaInvestigationActiveAdoptionRepository, SupabaseCapaInvestigationActiveAdoptionRepositoryError } from "../../lib/database/supabase/supabase-capa-investigation-active-adoption-repository";

let transactionSql: any;
vi.mock("../../lib/database/supabase/supabase-transactions", () => ({ requireSupabaseTransaction: vi.fn(() => transactionSql) }));

const ORG = "10000000-0000-4000-8000-000000000001";
const CASE_ID = "20000000-0000-4000-8000-000000000001";
const VERSION = "30000000-0000-4000-8000-000000000001";
const OUTPUT = "40000000-0000-4000-8000-000000000001";
const RUN = "50000000-0000-4000-8000-000000000001";
const OUTPUT_REQUEST = "60000000-0000-4000-8000-000000000001";
const OUTPUT_CORRELATION = "70000000-0000-4000-8000-000000000001";
const ADOPTION = "80000000-0000-4000-8000-000000000001";
const ADOPTION_REQUEST = "90000000-0000-4000-8000-000000000001";
const ADOPTION_CORRELATION = "a0000000-0000-4000-8000-000000000001";
const AUDIT = "b0000000-0000-4000-8000-000000000001";
const USER = "c0000000-0000-4000-8000-000000000001";
const AT = "2026-09-05T12:00:00.000Z";
const modelSafe = { trust: "model_safe_context", workflow_state: "S40", references: [] } as const;
const manifest = createCapaInvestigationActiveAdvisoryReferenceManifest({ reference_manifest: [], model_safe_context: modelSafe });
const proposal = { evidence_gaps: [{ proposal_key: "P1", gap: "Gap", why_it_matters: "Why", related_reference_keys: [], recommended_next_step: "Next", human_review_question: "Does this require review?" }], conflicting_information: [], assumptions: [], causal_hypotheses: [], alternative_hypotheses: [], investigation_recommendations: [] };
const payload = { proposal, uncertainty_and_limitations: [], citations: [], advisory_only: true, workflow_mutated: false, human_acceptance_required: true };

function adoption() {
  return constructCapaInvestigationActiveAdoption({ adoption_id: ADOPTION as never, organization_id: ORG as never, capa_case_id: CASE_ID as never, case_version_id: VERSION as never, record_version: 4, output_id: OUTPUT, proposal_key: "P1", proposal_category: "evidence_gap", adopted_item: { proposal_key: "P1", adopted_content: { gap: "Gap", why_it_matters: "Why", recommended_next_step: "Next" } }, resolved_reference_bindings: [], reference_manifest_schema_version: manifest.document.manifest_schema_version, reference_manifest_fingerprint_algorithm: manifest.fingerprint_algorithm, reference_manifest_sha256: manifest.reference_manifest_sha256, adopted_at: AT as never, adopted_by: { actor_type: "human", actor_id: USER }, request_id: ADOPTION_REQUEST as never, correlation_id: ADOPTION_CORRELATION as never, idempotency_key: "batch-1" as never, workflow_mutated: false, controlled_record_mutated: false, gate_approved: false });
}
function row(overrides: Record<string, unknown> = {}): any { const value = adoption(); return { organization_id: ORG, adoption_id: ADOPTION, output_id: OUTPUT, output_run_id: RUN, capa_case_id: CASE_ID, case_version_id: VERSION, record_version: 4, output_status: "completed_draft", output_request_id: OUTPUT_REQUEST, output_correlation_id: OUTPUT_CORRELATION, proposal_key: "P1", proposal_category: "evidence_gap", adopted_item: value.adopted_item, resolved_reference_bindings: [], reference_manifest_schema_version: manifest.document.manifest_schema_version, reference_manifest_fingerprint_algorithm: manifest.fingerprint_algorithm, reference_manifest_sha256: manifest.reference_manifest_sha256, adopted_at: AT, adopted_by_actor_type: "human", adopted_by_actor_id: USER, adoption_policy_version: value.adoption_policy_version, request_id: ADOPTION_REQUEST, correlation_id: ADOPTION_CORRELATION, idempotency_key: "batch-1", request_fingerprint: "d".repeat(64), audit_event_id: AUDIT, adoption_record: value, record_fingerprint_algorithm: "sha256", record_fingerprint: fingerprintCanonicalJson(value), workflow_mutated: false, controlled_record_mutated: false, gate_approved: false, ...overrides }; }
function output(overrides: Record<string, unknown> = {}): any { return { organization_id: ORG, output_id: OUTPUT, run_id: RUN, capa_case_id: CASE_ID, case_version_id: VERSION, record_version: 4, request_id: OUTPUT_REQUEST, correlation_id: OUTPUT_CORRELATION, status: "completed_draft", agent_id: "AG-RCA", agent_version: "ag-rca-1.0.0", output_schema_version: "capa_investigation_analysis_draft-1.0.0", advisory_only: true, workflow_mutated: false, human_acceptance_required: true, output_payload: payload, ...overrides }; }
function trace(overrides: Record<string, unknown> = {}): any { return { organization_id: ORG, output_id: OUTPUT, run_id: RUN, capa_case_id: CASE_ID, case_version_id: VERSION, record_version: 4, request_id: OUTPUT_REQUEST, correlation_id: OUTPUT_CORRELATION, output_status: "completed_draft", prompt_package: { package_schema_version: "capa-investigation-active-prompt-package-1.0.0", agent: { agent_id: "AG-RCA", agent_version: "ag-rca-1.0.0" }, generation_contract: { operation: "facilitate_root_cause", requested_output: "investigation_analysis_draft", output_schema_version: "capa_investigation_analysis_draft-1.0.0", store: false }, context_provenance: { model_safe_context: modelSafe } }, ...overrides }; }
function manifestRow(overrides: Record<string, unknown> = {}): any { return { organization_id: ORG, output_id: OUTPUT, run_id: RUN, capa_case_id: CASE_ID, case_version_id: VERSION, record_version: 4, request_id: OUTPUT_REQUEST, correlation_id: OUTPUT_CORRELATION, output_status: "completed_draft", manifest_schema_version: manifest.document.manifest_schema_version, fingerprint_algorithm: manifest.fingerprint_algorithm, reference_manifest: manifest.document, reference_manifest_sha256: manifest.reference_manifest_sha256, ...overrides }; }
function harness(...responses: unknown[]) { const queue = [...responses]; const calls: unknown[] = []; const tagged = vi.fn(async (strings: TemplateStringsArray, ...values: unknown[]) => { calls.push({ strings, values }); const next = queue.shift(); if (next instanceof Error) throw next; return next ?? []; }); transactionSql = Object.assign(tagged, { json: (value: unknown) => value }); return { calls, sql: tagged, transaction: { request_trace: { request_id: ADOPTION_REQUEST, correlation_id: ADOPTION_CORRELATION, idempotency_key: "batch-1" } } as never }; }
function input(overrides: Record<string, unknown> = {}): any { const value = adoption(); return { adoption: value, request_fingerprint: "d".repeat(64), record_fingerprint: fingerprintCanonicalJson(value), audit_event_id: AUDIT, ...overrides }; }
function validResponses(rowOverrides: Record<string, unknown> = {}) { return [[], [output()], [trace()], [manifestRow()], [{ current_version_id: VERSION, record_version: 4, status: "S40" }], [row(rowOverrides)]]; }

describe("Supabase S40 adoption repository", () => {
  it("persists and reconstructs a valid canonical adoption", async () => { const h = harness(...validResponses()); await expect(new SupabaseCapaInvestigationActiveAdoptionRepository(h.sql as never).appendAdoption(h.transaction, input())).resolves.toMatchObject({ status: "saved", record: { adoption: adoption() } }); expect(h.calls).toHaveLength(6); });
  it.each([["request", { request_trace: { request_id: "bad", correlation_id: ADOPTION_CORRELATION, idempotency_key: "batch-1" } }], ["correlation", { request_trace: { request_id: ADOPTION_REQUEST, correlation_id: "bad", idempotency_key: "batch-1" } }], ["idempotency", { request_trace: { request_id: ADOPTION_REQUEST, correlation_id: ADOPTION_CORRELATION, idempotency_key: "other" } }]])("rejects transaction %s mismatch", async (_name, override) => { const h = harness(); await expect(new SupabaseCapaInvestigationActiveAdoptionRepository(h.sql as never).appendAdoption({ ...(h.transaction as any), ...(override as any) } as never, input())).rejects.toThrow(SupabaseCapaInvestigationActiveAdoptionRepositoryError); expect(h.calls).toHaveLength(0); });
  it.each([["request fingerprint", { request_fingerprint: "bad" }], ["record fingerprint", { record_fingerprint: "bad" }], ["wrong record fingerprint", { record_fingerprint: "f".repeat(64) }], ["audit identity", { audit_event_id: "bad" }]])("rejects malformed or incorrect %s", async (_name, override) => { const h = harness(); await expect(new SupabaseCapaInvestigationActiveAdoptionRepository(h.sql as never).appendAdoption(h.transaction, input(override))).rejects.toThrow(SupabaseCapaInvestigationActiveAdoptionRepositoryError); expect(h.calls).toHaveLength(0); });
  it.each([["wrong record fingerprint", { record_fingerprint: "f".repeat(64) }], ["wrong algorithm", { record_fingerprint_algorithm: "md5" }], ["adoption record", { adoption_record: { changed: true } }], ["proposal category", { proposal_category: "assumption" }], ["bindings", { resolved_reference_bindings: [{ bad: true }] }], ["manifest metadata", { reference_manifest_sha256: "f".repeat(64) }], ["authority flag", { workflow_mutated: true }]])("rejects durable row with %s corruption", async (_name, override) => { const h = harness([row(override)]); await expect(new SupabaseCapaInvestigationActiveAdoptionRepository(h.sql as never).findAdoptionById(ORG, ADOPTION)).rejects.toThrow(SupabaseCapaInvestigationActiveAdoptionRepositoryError); });
  it.each([["missing output", []], ["wrong case", [output({ capa_case_id: "90000000-0000-4000-8000-000000000001" })]], ["wrong case version", [output({ case_version_id: "90000000-0000-4000-8000-000000000002" })]], ["wrong record version", [output({ record_version: 5 })]], ["wrong status", [output({ status: "service_failed" })]], ["wrong agent", [output({ agent_id: "AG-PLAN" })]], ["wrong agent version", [output({ agent_version: "ag-rca-0.0.0" })]], ["wrong schema", [output({ output_schema_version: "wrong" })]], ["payload advisory flag", [output({ output_payload: { ...payload, advisory_only: false } })]], ["payload workflow flag", [output({ output_payload: { ...payload, workflow_mutated: true } })]], ["payload acceptance flag", [output({ output_payload: { ...payload, human_acceptance_required: false } })]], ["unexpected payload field", [output({ output_payload: { ...payload, extra: true } })]], ["malformed proposal", [output({ output_payload: { ...payload, proposal: {} } })]], ["selected proposal missing", [output({ output_payload: { ...payload, proposal: { ...proposal, evidence_gaps: [] } } })]], ["duplicate selected proposal key", [output({ output_payload: { ...payload, proposal: { ...proposal, conflicting_information: [{ proposal_key: "P1", conflict: "Conflict", conflicting_reference_keys: [], why_it_matters: "Why", human_review_question: "Does this require review?" }] } } })]]])("rejects %s", async (_name, outputRows) => { const h = harness([], outputRows); await expect(new SupabaseCapaInvestigationActiveAdoptionRepository(h.sql as never).appendAdoption(h.transaction, input())).resolves.toMatchObject({ status: outputRows.length === 0 ? "output_not_found_or_not_authorized" : "output_not_adoptable" }); });
  it.each([["missing trace", []], ["duplicate trace", [trace(), trace()]], ["missing manifest", []], ["duplicate manifest", [manifestRow(), manifestRow()]]])("rejects %s", async (name, rows) => { const h = name.includes("trace") ? harness([], [output()], rows) : harness([], [output()], [trace()], rows); await expect(new SupabaseCapaInvestigationActiveAdoptionRepository(h.sql as never).appendAdoption(h.transaction, input())).resolves.toMatchObject({ status: "output_not_adoptable" }); });
  it.each([["trace run", { run_id: "bad" }], ["trace output", { output_id: "bad" }], ["trace case", { capa_case_id: "bad" }], ["trace version", { case_version_id: "bad" }], ["trace record", { record_version: 5 }], ["trace request", { request_id: "bad" }], ["trace correlation", { correlation_id: "bad" }], ["trace status", { output_status: "service_failed" }]])("rejects %s identity corruption", async (_name, override) => { const responses = validResponses(); responses[2] = [trace(override)]; const h = harness(...responses); await expect(new SupabaseCapaInvestigationActiveAdoptionRepository(h.sql as never).appendAdoption(h.transaction, input())).resolves.toMatchObject({ status: "output_not_adoptable" }); });
  it.each([["malformed prompt package", { prompt_package: {} }], ["wrong prompt agent", { prompt_package: { ...trace().prompt_package, agent: { agent_id: "AG-PLAN", agent_version: "ag-plan-1.0.0" } } }], ["wrong generation operation", { prompt_package: { ...trace().prompt_package, generation_contract: { ...trace().prompt_package.generation_contract, operation: "draft_investigation_plan" } } }], ["wrong requested output", { prompt_package: { ...trace().prompt_package, generation_contract: { ...trace().prompt_package.generation_contract, requested_output: "wrong" } } }], ["wrong output schema", { prompt_package: { ...trace().prompt_package, generation_contract: { ...trace().prompt_package.generation_contract, output_schema_version: "wrong" } } }], ["store enabled", { prompt_package: { ...trace().prompt_package, generation_contract: { ...trace().prompt_package.generation_contract, store: true } } }]])("rejects %s", async (_name, override) => { const responses = validResponses(); responses[2] = [trace(override)]; const h = harness(...responses); await expect(new SupabaseCapaInvestigationActiveAdoptionRepository(h.sql as never).appendAdoption(h.transaction, input())).resolves.toMatchObject({ status: "output_not_adoptable" }); });
  it.each([["malformed model-safe context", { prompt_package: { ...trace().prompt_package, context_provenance: { model_safe_context: {} } } }], ["malformed manifest", { reference_manifest: {} }], ["wrong manifest algorithm", { fingerprint_algorithm: "md5" }], ["wrong manifest SHA", { reference_manifest_sha256: "f".repeat(64) }]])("rejects %s", async (_name, override) => { const responses = validResponses(); if ("reference_manifest" in override) responses[3] = [manifestRow(override)]; else if ("fingerprint_algorithm" in override) responses[3] = [manifestRow(override)]; else if ("reference_manifest_sha256" in override) responses[3] = [manifestRow(override)]; else responses[2] = [trace(override)]; const h = harness(...responses); await expect(new SupabaseCapaInvestigationActiveAdoptionRepository(h.sql as never).appendAdoption(h.transaction, input())).resolves.toMatchObject({ status: "output_not_adoptable" }); });
  it.each([["wrong current version", { current_version_id: "90000000-0000-4000-8000-000000000001" }], ["wrong current record", { record_version: 5 }], ["wrong workflow", { status: "S30" }]])("classifies %s as case changed", async (_name, override) => { const responses = validResponses(); responses[4] = [ { current_version_id: VERSION, record_version: 4, status: "S40", ...override } ]; const h = harness(...responses); await expect(new SupabaseCapaInvestigationActiveAdoptionRepository(h.sql as never).appendAdoption(h.transaction, input())).resolves.toEqual({ status: "case_changed" }); });
  it("classifies exact replay and idempotency reuse without another append", async () => { const replay = harness([row()]); await expect(new SupabaseCapaInvestigationActiveAdoptionRepository(replay.sql as never).appendAdoption(replay.transaction, input())).resolves.toMatchObject({ status: "already_recorded" }); const conflict = harness([row({ request_fingerprint: "e".repeat(64) })]); await expect(new SupabaseCapaInvestigationActiveAdoptionRepository(conflict.sql as never).appendAdoption(conflict.transaction, input())).resolves.toMatchObject({ status: "conflict", reason_code: "IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_REQUEST" }); });
  it("fails closed when an insert race has no durable explanation", async () => { const h = harness([], [output()], [trace()], [manifestRow()], [{ current_version_id: VERSION, record_version: 4, status: "S40" }], [], []); await expect(new SupabaseCapaInvestigationActiveAdoptionRepository(h.sql as never).appendAdoption(h.transaction, input())).rejects.toThrow(SupabaseCapaInvestigationActiveAdoptionRepositoryError); });
});
