import { describe, expect, it, vi } from "vitest";
import { CAPA_INVESTIGATION_ACTIVE_WORKSPACE_DRAFT_SCHEMA_VERSION } from "../../lib/capa/application/capa-investigation-active-workspace-draft-contract";
import { SupabaseCapaInvestigationActiveWorkspaceDraftRepository, SupabaseCapaInvestigationActiveWorkspaceDraftRepositoryError } from "../../lib/database/supabase/supabase-capa-investigation-active-workspace-draft-repository";
let transactionSql: any;
vi.mock("../../lib/database/supabase/supabase-transactions", () => ({ requireSupabaseTransaction: vi.fn(() => transactionSql) }));
const ORG = "10000000-0000-4000-8000-000000000001"; const CASE = "20000000-0000-4000-8000-000000000001"; const AT = "2026-09-05T12:00:00.000Z";
function draft(revision = 1): any { return { schema_version: CAPA_INVESTIGATION_ACTIVE_WORKSPACE_DRAFT_SCHEMA_VERSION, trust: "untrusted_human_draft", workflow_state: "S40", organization_id: ORG, capa_case_id: CASE, case_version_id: "30000000-0000-4000-8000-000000000001", record_version: 4, draft_revision: revision, evidence_assumption_ledger: { items: [] }, root_cause_package: { hypotheses: [], root_cause_not_confirmed: null }, updated_by_user_id: "40000000-0000-4000-8000-000000000001", updated_at: AT }; }
function harness(...responses: unknown[]) { const queue = [...responses]; const calls: any[] = []; const sql = vi.fn(async (strings: TemplateStringsArray, ...values: unknown[]) => { calls.push({ text: strings.join("?"), values }); return queue.shift() ?? []; }); const tagged = Object.assign(sql, { json: (value: unknown) => value }); transactionSql = tagged; return { sql: tagged, calls, transaction: {} as never }; }
describe("Supabase S40 workspace draft repository", () => {
  it("finds only by organization and case, returns null when absent, and validates rows", async () => { const absent = harness([]); await expect(new SupabaseCapaInvestigationActiveWorkspaceDraftRepository(absent.sql as never).findDraft(ORG as never, CASE as never)).resolves.toBeNull(); expect(absent.calls[0].values).toEqual([ORG, CASE]); const valid = harness([draft()]); await expect(new SupabaseCapaInvestigationActiveWorkspaceDraftRepository(valid.sql as never).findDraft(ORG as never, CASE as never)).resolves.toMatchObject({ draft_revision: 1 }); const malformed = harness([{ ...draft(), trust: "authoritative_server_context" }]); await expect(new SupabaseCapaInvestigationActiveWorkspaceDraftRepository(malformed.sql as never).findDraft(ORG as never, CASE as never)).rejects.toThrow(SupabaseCapaInvestigationActiveWorkspaceDraftRepositoryError); });
  it("uses insert-on-conflict create CAS and rejects invalid initial revisions before SQL", async () => { const created = harness([draft()]); await expect(new SupabaseCapaInvestigationActiveWorkspaceDraftRepository(created.sql as never).saveDraft(created.transaction, { draft: draft(), expected_draft_revision: null })).resolves.toMatchObject({ status: "saved" }); expect(created.calls[0].text).toContain("insert into"); expect(created.calls[0].text).toContain("on conflict"); const collision = harness([]); await expect(new SupabaseCapaInvestigationActiveWorkspaceDraftRepository(collision.sql as never).saveDraft(collision.transaction, { draft: draft(), expected_draft_revision: null })).resolves.toEqual({ status: "concurrency_conflict" }); const invalid = harness(); await expect(new SupabaseCapaInvestigationActiveWorkspaceDraftRepository(invalid.sql as never).saveDraft(invalid.transaction, { draft: draft(2), expected_draft_revision: null })).resolves.toEqual({ status: "concurrency_conflict" }); expect(invalid.calls).toHaveLength(0); });
  it("uses one revision-constrained update statement and maps stale writes to conflicts", async () => { const updated = harness([draft(2)]); await expect(new SupabaseCapaInvestigationActiveWorkspaceDraftRepository(updated.sql as never).saveDraft(updated.transaction, { draft: draft(2), expected_draft_revision: 1 })).resolves.toMatchObject({ status: "saved" }); expect(updated.calls).toHaveLength(1); expect(updated.calls[0].text).toMatch(/update public\.capa_investigation_active_workspace_drafts[\s\S]*where organization_id = \?\s+and capa_case_id = \?\s+and draft_revision = \? returning \*/); expect(updated.calls[0].values).toEqual(expect.arrayContaining([ORG, CASE, 1])); for (const candidate of [draft(1), draft(3)]) { const h = harness(); await expect(new SupabaseCapaInvestigationActiveWorkspaceDraftRepository(h.sql as never).saveDraft(h.transaction, { draft: candidate, expected_draft_revision: 1 })).resolves.toEqual({ status: "concurrency_conflict" }); expect(h.calls).toHaveLength(0); } const stale = harness([]); await expect(new SupabaseCapaInvestigationActiveWorkspaceDraftRepository(stale.sql as never).saveDraft(stale.transaction, { draft: draft(2), expected_draft_revision: 1 })).resolves.toEqual({ status: "concurrency_conflict" }); });
  it("fails closed before persistence for malformed caller drafts and malformed returned rows", async () => { const caller = harness(); await expect(new SupabaseCapaInvestigationActiveWorkspaceDraftRepository(caller.sql as never).saveDraft(caller.transaction, { draft: { ...draft(), trust: "wrong" }, expected_draft_revision: null } as never)).rejects.toThrow(SupabaseCapaInvestigationActiveWorkspaceDraftRepositoryError); expect(caller.calls).toHaveLength(0); const returned = harness([{ ...draft(), evidence_assumption_ledger: { items: [{}] } }]); await expect(new SupabaseCapaInvestigationActiveWorkspaceDraftRepository(returned.sql as never).saveDraft(returned.transaction, { draft: draft(), expected_draft_revision: null })).rejects.toThrow(SupabaseCapaInvestigationActiveWorkspaceDraftRepositoryError); });
});
